// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: api/comment/v1/comment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommentAddFavorite = "/comment.v1.Comment/AddFavorite"
const OperationCommentCreateComment = "/comment.v1.Comment/CreateComment"
const OperationCommentDelFavorite = "/comment.v1.Comment/DelFavorite"
const OperationCommentLikeComment = "/comment.v1.Comment/LikeComment"
const OperationCommentListComments = "/comment.v1.Comment/ListComments"
const OperationCommentListFavorites = "/comment.v1.Comment/ListFavorites"
const OperationCommentReportComment = "/comment.v1.Comment/ReportComment"
const OperationCommentUnlikeComment = "/comment.v1.Comment/UnlikeComment"

type CommentHTTPServer interface {
	AddFavorite(context.Context, *AddFavoriteReq) (*FavoriteReply, error)
	// CreateComment 发表评论（内容 ≤2000 字符；chapter_id 缺省 = 书籍级评论）
	CreateComment(context.Context, *CreateCommentReq) (*CommentReply, error)
	DelFavorite(context.Context, *DelFavoriteReq) (*EmptyReply, error)
	LikeComment(context.Context, *LikeCommentReq) (*EmptyReply, error)
	// ListComments 评论列表：chapter_id 缺省 = 全部；0 = 仅书籍级
	ListComments(context.Context, *ListCommentsReq) (*ListCommentsReply, error)
	ListFavorites(context.Context, *ListFavoritesReq) (*ListFavoritesReply, error)
	// ReportComment 举报：置 status=2 待审核
	ReportComment(context.Context, *ReportCommentReq) (*EmptyReply, error)
	UnlikeComment(context.Context, *UnlikeCommentReq) (*EmptyReply, error)
}

func RegisterCommentHTTPServer(s *http.Server, srv CommentHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/comments", _Comment_CreateComment0_HTTP_Handler(srv))
	r.GET("/api/v1/comments", _Comment_ListComments0_HTTP_Handler(srv))
	r.POST("/api/v1/comments/{id}/like", _Comment_LikeComment0_HTTP_Handler(srv))
	r.DELETE("/api/v1/comments/{id}/like", _Comment_UnlikeComment0_HTTP_Handler(srv))
	r.POST("/api/v1/comments/{id}/report", _Comment_ReportComment0_HTTP_Handler(srv))
	r.POST("/api/v1/books/{book_id}/favorite", _Comment_AddFavorite0_HTTP_Handler(srv))
	r.DELETE("/api/v1/books/{book_id}/favorite", _Comment_DelFavorite0_HTTP_Handler(srv))
	r.GET("/api/v1/favorites", _Comment_ListFavorites0_HTTP_Handler(srv))
}

func _Comment_CreateComment0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCommentReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentCreateComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateComment(ctx, req.(*CreateCommentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CommentReply)
		return ctx.Result(200, reply)
	}
}

func _Comment_ListComments0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCommentsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentListComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListComments(ctx, req.(*ListCommentsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _Comment_LikeComment0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LikeCommentReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentLikeComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LikeComment(ctx, req.(*LikeCommentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Comment_UnlikeComment0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnlikeCommentReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentUnlikeComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnlikeComment(ctx, req.(*UnlikeCommentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Comment_ReportComment0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReportCommentReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentReportComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReportComment(ctx, req.(*ReportCommentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Comment_AddFavorite0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddFavoriteReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentAddFavorite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddFavorite(ctx, req.(*AddFavoriteReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FavoriteReply)
		return ctx.Result(200, reply)
	}
}

func _Comment_DelFavorite0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DelFavoriteReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentDelFavorite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DelFavorite(ctx, req.(*DelFavoriteReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Comment_ListFavorites0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFavoritesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentListFavorites)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFavorites(ctx, req.(*ListFavoritesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFavoritesReply)
		return ctx.Result(200, reply)
	}
}

type CommentHTTPClient interface {
	AddFavorite(ctx context.Context, req *AddFavoriteReq, opts ...http.CallOption) (rsp *FavoriteReply, err error)
	// CreateComment 发表评论（内容 ≤2000 字符；chapter_id 缺省 = 书籍级评论）
	CreateComment(ctx context.Context, req *CreateCommentReq, opts ...http.CallOption) (rsp *CommentReply, err error)
	DelFavorite(ctx context.Context, req *DelFavoriteReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
	LikeComment(ctx context.Context, req *LikeCommentReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// ListComments 评论列表：chapter_id 缺省 = 全部；0 = 仅书籍级
	ListComments(ctx context.Context, req *ListCommentsReq, opts ...http.CallOption) (rsp *ListCommentsReply, err error)
	ListFavorites(ctx context.Context, req *ListFavoritesReq, opts ...http.CallOption) (rsp *ListFavoritesReply, err error)
	// ReportComment 举报：置 status=2 待审核
	ReportComment(ctx context.Context, req *ReportCommentReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
	UnlikeComment(ctx context.Context, req *UnlikeCommentReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
}

type CommentHTTPClientImpl struct {
	cc *http.Client
}

func NewCommentHTTPClient(client *http.Client) CommentHTTPClient {
	return &CommentHTTPClientImpl{client}
}

func (c *CommentHTTPClientImpl) AddFavorite(ctx context.Context, in *AddFavoriteReq, opts ...http.CallOption) (*FavoriteReply, error) {
	var out FavoriteReply
	pattern := "/api/v1/books/{book_id}/favorite"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentAddFavorite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateComment 发表评论（内容 ≤2000 字符；chapter_id 缺省 = 书籍级评论）
func (c *CommentHTTPClientImpl) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...http.CallOption) (*CommentReply, error) {
	var out CommentReply
	pattern := "/api/v1/comments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommentCreateComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommentHTTPClientImpl) DelFavorite(ctx context.Context, in *DelFavoriteReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/v1/books/{book_id}/favorite"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentDelFavorite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommentHTTPClientImpl) LikeComment(ctx context.Context, in *LikeCommentReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/v1/comments/{id}/like"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentLikeComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListComments 评论列表：chapter_id 缺省 = 全部；0 = 仅书籍级
func (c *CommentHTTPClientImpl) ListComments(ctx context.Context, in *ListCommentsReq, opts ...http.CallOption) (*ListCommentsReply, error) {
	var out ListCommentsReply
	pattern := "/api/v1/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentListComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommentHTTPClientImpl) ListFavorites(ctx context.Context, in *ListFavoritesReq, opts ...http.CallOption) (*ListFavoritesReply, error) {
	var out ListFavoritesReply
	pattern := "/api/v1/favorites"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentListFavorites))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReportComment 举报：置 status=2 待审核
func (c *CommentHTTPClientImpl) ReportComment(ctx context.Context, in *ReportCommentReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/v1/comments/{id}/report"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentReportComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommentHTTPClientImpl) UnlikeComment(ctx context.Context, in *UnlikeCommentReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/v1/comments/{id}/like"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentUnlikeComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
