// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: admin/v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminCreateCategory = "/admin.v1.Admin/CreateCategory"
const OperationAdminCreateTag = "/admin.v1.Admin/CreateTag"
const OperationAdminDeleteCategory = "/admin.v1.Admin/DeleteCategory"
const OperationAdminDeleteTag = "/admin.v1.Admin/DeleteTag"
const OperationAdminGetStats = "/admin.v1.Admin/GetStats"
const OperationAdminListAuditLogs = "/admin.v1.Admin/ListAuditLogs"
const OperationAdminListCategories = "/admin.v1.Admin/ListCategories"
const OperationAdminListTags = "/admin.v1.Admin/ListTags"
const OperationAdminTranslateBook = "/admin.v1.Admin/TranslateBook"
const OperationAdminTranslateBookChapters = "/admin.v1.Admin/TranslateBookChapters"
const OperationAdminUpdateCategory = "/admin.v1.Admin/UpdateCategory"
const OperationAdminUpdateTag = "/admin.v1.Admin/UpdateTag"

type AdminHTTPServer interface {
	CreateCategory(context.Context, *CreateCategoryReq) (*CategoryReply, error)
	CreateTag(context.Context, *CreateTagReq) (*TagReply, error)
	DeleteCategory(context.Context, *DeleteCategoryReq) (*EmptyReply, error)
	DeleteTag(context.Context, *DeleteTagReq) (*EmptyReply, error)
	// GetStats 仪表盘统计：书籍/用户/评论数、DAU 近似、热门书籍/热门搜索词（requireAdmin）
	GetStats(context.Context, *GetStatsReq) (*GetStatsReply, error)
	// ListAuditLogs 审计日志分页查询（requireAdmin，支持用户/动作/目标/时间范围筛选）
	ListAuditLogs(context.Context, *ListAuditLogsReq) (*ListAuditLogsReply, error)
	// ListCategories 分类列表（requireAdmin，全量返回，量小）
	// 独立路径 /api/admin/categories：与 book 服务公开 GET /api/categories 区分（gorilla/mux 先注册优先）
	ListCategories(context.Context, *ListCategoriesReq) (*ListCategoriesReply, error)
	// ListTags 标签列表（requireAdmin）
	ListTags(context.Context, *ListTagsReq) (*ListTagsReply, error)
	// TranslateBook 翻译书籍标题与简介到指定语言（requireAdmin；源文本取书籍原始语言，DeepL）
	TranslateBook(context.Context, *TranslateBookReq) (*TranslateBookReply, error)
	// TranslateBookChapters 翻译书籍全部章节到指定语言（requireAdmin；同步串行，单章失败不中断）
	TranslateBookChapters(context.Context, *TranslateBookChaptersReq) (*TranslateBookChaptersReply, error)
	// UpdateCategory 更新分类；字段可选，仅更新非空项
	UpdateCategory(context.Context, *UpdateCategoryReq) (*CategoryReply, error)
	UpdateTag(context.Context, *UpdateTagReq) (*TagReply, error)
}

func RegisterAdminHTTPServer(s *http.Server, srv AdminHTTPServer) {
	r := s.Route("/")
	r.GET("/api/stats/overview", _Admin_GetStats0_HTTP_Handler(srv))
	r.GET("/api/admin/audit-logs", _Admin_ListAuditLogs0_HTTP_Handler(srv))
	r.GET("/api/admin/categories", _Admin_ListCategories0_HTTP_Handler(srv))
	r.POST("/api/categories", _Admin_CreateCategory0_HTTP_Handler(srv))
	r.PUT("/api/categories/{id}", _Admin_UpdateCategory0_HTTP_Handler(srv))
	r.DELETE("/api/categories/{id}", _Admin_DeleteCategory0_HTTP_Handler(srv))
	r.GET("/api/admin/tags", _Admin_ListTags0_HTTP_Handler(srv))
	r.POST("/api/tags", _Admin_CreateTag0_HTTP_Handler(srv))
	r.PUT("/api/tags/{id}", _Admin_UpdateTag0_HTTP_Handler(srv))
	r.DELETE("/api/tags/{id}", _Admin_DeleteTag0_HTTP_Handler(srv))
	r.POST("/api/admin/translate/book/{book_id}", _Admin_TranslateBook0_HTTP_Handler(srv))
	r.POST("/api/admin/translate/book/{book_id}/chapters", _Admin_TranslateBookChapters0_HTTP_Handler(srv))
}

func _Admin_GetStats0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStatsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminGetStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStats(ctx, req.(*GetStatsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStatsReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListAuditLogs0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAuditLogsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListAuditLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAuditLogs(ctx, req.(*ListAuditLogsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAuditLogsReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListCategories0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCategoriesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCategories(ctx, req.(*ListCategoriesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCategoriesReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_CreateCategory0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCategoryReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminCreateCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCategory(ctx, req.(*CreateCategoryReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CategoryReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_UpdateCategory0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCategoryReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUpdateCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCategory(ctx, req.(*UpdateCategoryReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CategoryReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_DeleteCategory0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCategoryReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminDeleteCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCategory(ctx, req.(*DeleteCategoryReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListTags0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTagsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTags(ctx, req.(*ListTagsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTagsReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_CreateTag0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTagReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminCreateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTag(ctx, req.(*CreateTagReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TagReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_UpdateTag0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTagReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUpdateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTag(ctx, req.(*UpdateTagReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TagReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_DeleteTag0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTagReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminDeleteTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTag(ctx, req.(*DeleteTagReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_TranslateBook0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TranslateBookReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminTranslateBook)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TranslateBook(ctx, req.(*TranslateBookReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TranslateBookReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_TranslateBookChapters0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TranslateBookChaptersReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminTranslateBookChapters)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TranslateBookChapters(ctx, req.(*TranslateBookChaptersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TranslateBookChaptersReply)
		return ctx.Result(200, reply)
	}
}

type AdminHTTPClient interface {
	CreateCategory(ctx context.Context, req *CreateCategoryReq, opts ...http.CallOption) (rsp *CategoryReply, err error)
	CreateTag(ctx context.Context, req *CreateTagReq, opts ...http.CallOption) (rsp *TagReply, err error)
	DeleteCategory(ctx context.Context, req *DeleteCategoryReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
	DeleteTag(ctx context.Context, req *DeleteTagReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// GetStats 仪表盘统计：书籍/用户/评论数、DAU 近似、热门书籍/热门搜索词（requireAdmin）
	GetStats(ctx context.Context, req *GetStatsReq, opts ...http.CallOption) (rsp *GetStatsReply, err error)
	// ListAuditLogs 审计日志分页查询（requireAdmin，支持用户/动作/目标/时间范围筛选）
	ListAuditLogs(ctx context.Context, req *ListAuditLogsReq, opts ...http.CallOption) (rsp *ListAuditLogsReply, err error)
	// ListCategories 分类列表（requireAdmin，全量返回，量小）
	// 独立路径 /api/admin/categories：与 book 服务公开 GET /api/categories 区分（gorilla/mux 先注册优先）
	ListCategories(ctx context.Context, req *ListCategoriesReq, opts ...http.CallOption) (rsp *ListCategoriesReply, err error)
	// ListTags 标签列表（requireAdmin）
	ListTags(ctx context.Context, req *ListTagsReq, opts ...http.CallOption) (rsp *ListTagsReply, err error)
	// TranslateBook 翻译书籍标题与简介到指定语言（requireAdmin；源文本取书籍原始语言，DeepL）
	TranslateBook(ctx context.Context, req *TranslateBookReq, opts ...http.CallOption) (rsp *TranslateBookReply, err error)
	// TranslateBookChapters 翻译书籍全部章节到指定语言（requireAdmin；同步串行，单章失败不中断）
	TranslateBookChapters(ctx context.Context, req *TranslateBookChaptersReq, opts ...http.CallOption) (rsp *TranslateBookChaptersReply, err error)
	// UpdateCategory 更新分类；字段可选，仅更新非空项
	UpdateCategory(ctx context.Context, req *UpdateCategoryReq, opts ...http.CallOption) (rsp *CategoryReply, err error)
	UpdateTag(ctx context.Context, req *UpdateTagReq, opts ...http.CallOption) (rsp *TagReply, err error)
}

type AdminHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminHTTPClient(client *http.Client) AdminHTTPClient {
	return &AdminHTTPClientImpl{client}
}

func (c *AdminHTTPClientImpl) CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...http.CallOption) (*CategoryReply, error) {
	var out CategoryReply
	pattern := "/api/categories"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminCreateCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) CreateTag(ctx context.Context, in *CreateTagReq, opts ...http.CallOption) (*TagReply, error) {
	var out TagReply
	pattern := "/api/tags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminCreateTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/categories/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminDeleteCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) DeleteTag(ctx context.Context, in *DeleteTagReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/tags/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminDeleteTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStats 仪表盘统计：书籍/用户/评论数、DAU 近似、热门书籍/热门搜索词（requireAdmin）
func (c *AdminHTTPClientImpl) GetStats(ctx context.Context, in *GetStatsReq, opts ...http.CallOption) (*GetStatsReply, error) {
	var out GetStatsReply
	pattern := "/api/stats/overview"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminGetStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAuditLogs 审计日志分页查询（requireAdmin，支持用户/动作/目标/时间范围筛选）
func (c *AdminHTTPClientImpl) ListAuditLogs(ctx context.Context, in *ListAuditLogsReq, opts ...http.CallOption) (*ListAuditLogsReply, error) {
	var out ListAuditLogsReply
	pattern := "/api/admin/audit-logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListAuditLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCategories 分类列表（requireAdmin，全量返回，量小）
// 独立路径 /api/admin/categories：与 book 服务公开 GET /api/categories 区分（gorilla/mux 先注册优先）
func (c *AdminHTTPClientImpl) ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...http.CallOption) (*ListCategoriesReply, error) {
	var out ListCategoriesReply
	pattern := "/api/admin/categories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListCategories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTags 标签列表（requireAdmin）
func (c *AdminHTTPClientImpl) ListTags(ctx context.Context, in *ListTagsReq, opts ...http.CallOption) (*ListTagsReply, error) {
	var out ListTagsReply
	pattern := "/api/admin/tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TranslateBook 翻译书籍标题与简介到指定语言（requireAdmin；源文本取书籍原始语言，DeepL）
func (c *AdminHTTPClientImpl) TranslateBook(ctx context.Context, in *TranslateBookReq, opts ...http.CallOption) (*TranslateBookReply, error) {
	var out TranslateBookReply
	pattern := "/api/admin/translate/book/{book_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminTranslateBook))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TranslateBookChapters 翻译书籍全部章节到指定语言（requireAdmin；同步串行，单章失败不中断）
func (c *AdminHTTPClientImpl) TranslateBookChapters(ctx context.Context, in *TranslateBookChaptersReq, opts ...http.CallOption) (*TranslateBookChaptersReply, error) {
	var out TranslateBookChaptersReply
	pattern := "/api/admin/translate/book/{book_id}/chapters"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminTranslateBookChapters))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCategory 更新分类；字段可选，仅更新非空项
func (c *AdminHTTPClientImpl) UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...http.CallOption) (*CategoryReply, error) {
	var out CategoryReply
	pattern := "/api/categories/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUpdateCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) UpdateTag(ctx context.Context, in *UpdateTagReq, opts ...http.CallOption) (*TagReply, error) {
	var out TagReply
	pattern := "/api/tags/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUpdateTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
