// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: admin/v1/admin.proto

// 管理端服务：仪表盘统计 / 分类 / 标签（T-A-14/16）
// 业务码段 18xxxx；REST 映射 /api/stats/overview、/api/admin/categories、/api/admin/tags

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsReq) Reset() {
	*x = GetStatsReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReq) ProtoMessage() {}

func (x *GetStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReq.ProtoReflect.Descriptor instead.
func (*GetStatsReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type GetStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookCount     int64                  `protobuf:"varint,1,opt,name=book_count,json=bookCount,proto3" json:"book_count,omitempty"`
	UserCount     int64                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	Dau           int64                  `protobuf:"varint,4,opt,name=dau,proto3" json:"dau,omitempty"`                                   // DAU 近似：当日登录 + 当日搜索的去重用户
	HotBooks      []*HotBook             `protobuf:"bytes,5,rep,name=hot_books,json=hotBooks,proto3" json:"hot_books,omitempty"`          // 热门书籍（复用搜索热门榜）
	HotKeywords   []*HotKeyword          `protobuf:"bytes,6,rep,name=hot_keywords,json=hotKeywords,proto3" json:"hot_keywords,omitempty"` // 热门搜索词（搜索日志聚合）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsReply) Reset() {
	*x = GetStatsReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReply) ProtoMessage() {}

func (x *GetStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReply.ProtoReflect.Descriptor instead.
func (*GetStatsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsReply) GetBookCount() int64 {
	if x != nil {
		return x.BookCount
	}
	return 0
}

func (x *GetStatsReply) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *GetStatsReply) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *GetStatsReply) GetDau() int64 {
	if x != nil {
		return x.Dau
	}
	return 0
}

func (x *GetStatsReply) GetHotBooks() []*HotBook {
	if x != nil {
		return x.HotBooks
	}
	return nil
}

func (x *GetStatsReply) GetHotKeywords() []*HotKeyword {
	if x != nil {
		return x.HotKeywords
	}
	return nil
}

type HotBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Hot           int64                  `protobuf:"varint,3,opt,name=hot,proto3" json:"hot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotBook) Reset() {
	*x = HotBook{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotBook) ProtoMessage() {}

func (x *HotBook) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotBook.ProtoReflect.Descriptor instead.
func (*HotBook) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *HotBook) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *HotBook) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HotBook) GetHot() int64 {
	if x != nil {
		return x.Hot
	}
	return 0
}

type HotKeyword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotKeyword) Reset() {
	*x = HotKeyword{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotKeyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotKeyword) ProtoMessage() {}

func (x *HotKeyword) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotKeyword.ProtoReflect.Descriptor instead.
func (*HotKeyword) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *HotKeyword) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *HotKeyword) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CategoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryReply) Reset() {
	*x = CategoryReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryReply) ProtoMessage() {}

func (x *CategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryReply.ProtoReflect.Descriptor instead.
func (*CategoryReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategoryReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategoryReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CategoryReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListCategoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesReq) Reset() {
	*x = ListCategoriesReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesReq) ProtoMessage() {}

func (x *ListCategoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesReq.ProtoReflect.Descriptor instead.
func (*ListCategoriesReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

type ListCategoriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CategoryReply       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesReply) Reset() {
	*x = ListCategoriesReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesReply) ProtoMessage() {}

func (x *ListCategoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesReply.ProtoReflect.Descriptor instead.
func (*ListCategoriesReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListCategoriesReply) GetList() []*CategoryReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListCategoriesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 0=一级分类
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryReq) Reset() {
	*x = CreateCategoryReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryReq) ProtoMessage() {}

func (x *CreateCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryReq.ProtoReflect.Descriptor instead.
func (*CreateCategoryReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCategoryReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCategoryReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	Status        *int32                 `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"` // 0 禁用 1 启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryReq) Reset() {
	*x = UpdateCategoryReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryReq) ProtoMessage() {}

func (x *UpdateCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryReq.ProtoReflect.Descriptor instead.
func (*UpdateCategoryReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCategoryReq) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *UpdateCategoryReq) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

func (x *UpdateCategoryReq) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type DeleteCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryReq) Reset() {
	*x = DeleteCategoryReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryReq) ProtoMessage() {}

func (x *DeleteCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryReq.ProtoReflect.Descriptor instead.
func (*DeleteCategoryReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagReply) Reset() {
	*x = TagReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagReply) ProtoMessage() {}

func (x *TagReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagReply.ProtoReflect.Descriptor instead.
func (*TagReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *TagReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TagReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TagReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListTagsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsReq) Reset() {
	*x = ListTagsReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsReq) ProtoMessage() {}

func (x *ListTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsReq.ProtoReflect.Descriptor instead.
func (*ListTagsReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

type ListTagsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TagReply            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsReply) Reset() {
	*x = ListTagsReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsReply) ProtoMessage() {}

func (x *ListTagsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsReply.ProtoReflect.Descriptor instead.
func (*ListTagsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListTagsReply) GetList() []*TagReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTagsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"` // 缺省 zh-CN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagReq) Reset() {
	*x = CreateTagReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagReq) ProtoMessage() {}

func (x *CreateTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagReq.ProtoReflect.Descriptor instead.
func (*CreateTagReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type UpdateTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Lang          *string                `protobuf:"bytes,3,opt,name=lang,proto3,oneof" json:"lang,omitempty"`
	Status        *int32                 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"` // 0 禁用 1 启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagReq) Reset() {
	*x = UpdateTagReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagReq) ProtoMessage() {}

func (x *UpdateTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagReq.ProtoReflect.Descriptor instead.
func (*UpdateTagReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateTagReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTagReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTagReq) GetLang() string {
	if x != nil && x.Lang != nil {
		return *x.Lang
	}
	return ""
}

func (x *UpdateTagReq) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type DeleteTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagReq) Reset() {
	*x = DeleteTagReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagReq) ProtoMessage() {}

func (x *DeleteTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagReq.ProtoReflect.Descriptor instead.
func (*DeleteTagReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteTagReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

type TranslateBookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"` // 目标语言（zh-CN/en/ja/ko/fr/de/es/ru/pt/hi/ar/id；bn 不支持）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateBookReq) Reset() {
	*x = TranslateBookReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateBookReq) ProtoMessage() {}

func (x *TranslateBookReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateBookReq.ProtoReflect.Descriptor instead.
func (*TranslateBookReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *TranslateBookReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *TranslateBookReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type TranslateBookReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`     // 翻译后的标题
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"` // 翻译后的简介
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateBookReply) Reset() {
	*x = TranslateBookReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateBookReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateBookReply) ProtoMessage() {}

func (x *TranslateBookReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateBookReply.ProtoReflect.Descriptor instead.
func (*TranslateBookReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *TranslateBookReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *TranslateBookReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TranslateBookReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TranslateBookReply) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type TranslateBookChaptersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateBookChaptersReq) Reset() {
	*x = TranslateBookChaptersReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateBookChaptersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateBookChaptersReq) ProtoMessage() {}

func (x *TranslateBookChaptersReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateBookChaptersReq.ProtoReflect.Descriptor instead.
func (*TranslateBookChaptersReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *TranslateBookChaptersReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *TranslateBookChaptersReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type TranslateBookChaptersReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BookId         int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Lang           string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Total          int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Succeeded      int32                  `protobuf:"varint,4,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed         int32                  `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	FailedChapters []int32                `protobuf:"varint,6,rep,packed,name=failed_chapters,json=failedChapters,proto3" json:"failed_chapters,omitempty"` // 失败章节号（chapter_no）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateBookChaptersReply) Reset() {
	*x = TranslateBookChaptersReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateBookChaptersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateBookChaptersReply) ProtoMessage() {}

func (x *TranslateBookChaptersReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateBookChaptersReply.ProtoReflect.Descriptor instead.
func (*TranslateBookChaptersReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *TranslateBookChaptersReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *TranslateBookChaptersReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TranslateBookChaptersReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TranslateBookChaptersReply) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *TranslateBookChaptersReply) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *TranslateBookChaptersReply) GetFailedChapters() []int32 {
	if x != nil {
		return x.FailedChapters
	}
	return nil
}

type ListAuditLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // 0=全部
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                           // 空=全部
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 空=全部
	TargetId      int64                  `protobuf:"varint,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`      // 0=全部
	StartTime     string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // created_at >=（RFC3339 或日期）
	EndTime       string                 `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`          // created_at <=
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsReq) Reset() {
	*x = ListAuditLogsReq{}
	mi := &file_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsReq) ProtoMessage() {}

func (x *ListAuditLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsReq.ProtoReflect.Descriptor instead.
func (*ListAuditLogsReq) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListAuditLogsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuditLogsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditLogsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAuditLogsReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditLogsReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ListAuditLogsReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ListAuditLogsReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ListAuditLogsReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type AuditLogReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogReply) Reset() {
	*x = AuditLogReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogReply) ProtoMessage() {}

func (x *AuditLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogReply.ProtoReflect.Descriptor instead.
func (*AuditLogReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *AuditLogReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditLogReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuditLogReply) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogReply) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditLogReply) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *AuditLogReply) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AuditLogReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditLogReply) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLogReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListAuditLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AuditLogReply       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsReply) Reset() {
	*x = ListAuditLogsReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsReply) ProtoMessage() {}

func (x *ListAuditLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsReply.ProtoReflect.Descriptor instead.
func (*ListAuditLogsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *ListAuditLogsReply) GetList() []*AuditLogReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAuditLogsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\"\r\n" +
	"\vGetStatsReq\"\xed\x01\n" +
	"\rGetStatsReply\x12\x1d\n" +
	"\n" +
	"book_count\x18\x01 \x01(\x03R\tbookCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x03R\tuserCount\x12#\n" +
	"\rcomment_count\x18\x03 \x01(\x03R\fcommentCount\x12\x10\n" +
	"\x03dau\x18\x04 \x01(\x03R\x03dau\x12.\n" +
	"\thot_books\x18\x05 \x03(\v2\x11.admin.v1.HotBookR\bhotBooks\x127\n" +
	"\fhot_keywords\x18\x06 \x03(\v2\x14.admin.v1.HotKeywordR\vhotKeywords\"J\n" +
	"\aHotBook\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03hot\x18\x03 \x01(\x03R\x03hot\"<\n" +
	"\n" +
	"HotKeyword\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xa6\x01\n" +
	"\rCategoryReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x13\n" +
	"\x11ListCategoriesReq\"X\n" +
	"\x13ListCategoriesReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.admin.v1.CategoryReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"c\n" +
	"\x11CreateCategoryReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"\xd0\x01\n" +
	"\x11UpdateCategoryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x03H\x01R\bparentId\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05H\x02R\tsortOrder\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\x05H\x03R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_sort_orderB\t\n" +
	"\a_status\"#\n" +
	"\x11DeleteCategoryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"y\n" +
	"\bTagReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\r\n" +
	"\vListTagsReq\"M\n" +
	"\rListTagsReply\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.admin.v1.TagReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"6\n" +
	"\fCreateTagReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"\x8a\x01\n" +
	"\fUpdateTagReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04lang\x18\x03 \x01(\tH\x01R\x04lang\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x05H\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_langB\t\n" +
	"\a_status\"\x1e\n" +
	"\fDeleteTagReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\f\n" +
	"\n" +
	"EmptyReply\"?\n" +
	"\x10TranslateBookReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"q\n" +
	"\x12TranslateBookReply\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"G\n" +
	"\x18TranslateBookChaptersReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"\xbe\x01\n" +
	"\x1aTranslateBookChaptersReply\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1c\n" +
	"\tsucceeded\x18\x04 \x01(\x05R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x05 \x01(\x05R\x06failed\x12'\n" +
	"\x0ffailed_chapters\x18\x06 \x03(\x05R\x0efailedChapters\"\xec\x01\n" +
	"\x10ListAuditLogsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\x03R\btargetId\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\tR\aendTime\"\xf4\x01\n" +
	"\rAuditLogReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"W\n" +
	"\x12ListAuditLogsReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.admin.v1.AuditLogReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xca\t\n" +
	"\x05Admin\x12W\n" +
	"\bGetStats\x12\x15.admin.v1.GetStatsReq\x1a\x17.admin.v1.GetStatsReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/stats/overview\x12h\n" +
	"\rListAuditLogs\x12\x1a.admin.v1.ListAuditLogsReq\x1a\x1c.admin.v1.ListAuditLogsReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/admin/audit-logs\x12k\n" +
	"\x0eListCategories\x12\x1b.admin.v1.ListCategoriesReq\x1a\x1d.admin.v1.ListCategoriesReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/admin/categories\x12b\n" +
	"\x0eCreateCategory\x12\x1b.admin.v1.CreateCategoryReq\x1a\x17.admin.v1.CategoryReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/categories\x12g\n" +
	"\x0eUpdateCategory\x12\x1b.admin.v1.UpdateCategoryReq\x1a\x17.admin.v1.CategoryReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/categories/{id}\x12a\n" +
	"\x0eDeleteCategory\x12\x1b.admin.v1.DeleteCategoryReq\x1a\x14.admin.v1.EmptyReply\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/categories/{id}\x12S\n" +
	"\bListTags\x12\x15.admin.v1.ListTagsReq\x1a\x17.admin.v1.ListTagsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/admin/tags\x12M\n" +
	"\tCreateTag\x12\x16.admin.v1.CreateTagReq\x1a\x12.admin.v1.TagReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/tags\x12R\n" +
	"\tUpdateTag\x12\x16.admin.v1.UpdateTagReq\x1a\x12.admin.v1.TagReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/api/tags/{id}\x12Q\n" +
	"\tDeleteTag\x12\x16.admin.v1.DeleteTagReq\x1a\x14.admin.v1.EmptyReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/api/tags/{id}\x12y\n" +
	"\rTranslateBook\x12\x1a.admin.v1.TranslateBookReq\x1a\x1c.admin.v1.TranslateBookReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/admin/translate/book/{book_id}\x12\x9a\x01\n" +
	"\x15TranslateBookChapters\x12\".admin.v1.TranslateBookChaptersReq\x1a$.admin.v1.TranslateBookChaptersReply\"7\x82\xd3\xe4\x93\x021:\x01*\",/api/admin/translate/book/{book_id}/chaptersB$Z\"open-novel/backend/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_admin_v1_admin_proto_goTypes = []any{
	(*GetStatsReq)(nil),                // 0: admin.v1.GetStatsReq
	(*GetStatsReply)(nil),              // 1: admin.v1.GetStatsReply
	(*HotBook)(nil),                    // 2: admin.v1.HotBook
	(*HotKeyword)(nil),                 // 3: admin.v1.HotKeyword
	(*CategoryReply)(nil),              // 4: admin.v1.CategoryReply
	(*ListCategoriesReq)(nil),          // 5: admin.v1.ListCategoriesReq
	(*ListCategoriesReply)(nil),        // 6: admin.v1.ListCategoriesReply
	(*CreateCategoryReq)(nil),          // 7: admin.v1.CreateCategoryReq
	(*UpdateCategoryReq)(nil),          // 8: admin.v1.UpdateCategoryReq
	(*DeleteCategoryReq)(nil),          // 9: admin.v1.DeleteCategoryReq
	(*TagReply)(nil),                   // 10: admin.v1.TagReply
	(*ListTagsReq)(nil),                // 11: admin.v1.ListTagsReq
	(*ListTagsReply)(nil),              // 12: admin.v1.ListTagsReply
	(*CreateTagReq)(nil),               // 13: admin.v1.CreateTagReq
	(*UpdateTagReq)(nil),               // 14: admin.v1.UpdateTagReq
	(*DeleteTagReq)(nil),               // 15: admin.v1.DeleteTagReq
	(*EmptyReply)(nil),                 // 16: admin.v1.EmptyReply
	(*TranslateBookReq)(nil),           // 17: admin.v1.TranslateBookReq
	(*TranslateBookReply)(nil),         // 18: admin.v1.TranslateBookReply
	(*TranslateBookChaptersReq)(nil),   // 19: admin.v1.TranslateBookChaptersReq
	(*TranslateBookChaptersReply)(nil), // 20: admin.v1.TranslateBookChaptersReply
	(*ListAuditLogsReq)(nil),           // 21: admin.v1.ListAuditLogsReq
	(*AuditLogReply)(nil),              // 22: admin.v1.AuditLogReply
	(*ListAuditLogsReply)(nil),         // 23: admin.v1.ListAuditLogsReply
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	2,  // 0: admin.v1.GetStatsReply.hot_books:type_name -> admin.v1.HotBook
	3,  // 1: admin.v1.GetStatsReply.hot_keywords:type_name -> admin.v1.HotKeyword
	4,  // 2: admin.v1.ListCategoriesReply.list:type_name -> admin.v1.CategoryReply
	10, // 3: admin.v1.ListTagsReply.list:type_name -> admin.v1.TagReply
	22, // 4: admin.v1.ListAuditLogsReply.list:type_name -> admin.v1.AuditLogReply
	0,  // 5: admin.v1.Admin.GetStats:input_type -> admin.v1.GetStatsReq
	21, // 6: admin.v1.Admin.ListAuditLogs:input_type -> admin.v1.ListAuditLogsReq
	5,  // 7: admin.v1.Admin.ListCategories:input_type -> admin.v1.ListCategoriesReq
	7,  // 8: admin.v1.Admin.CreateCategory:input_type -> admin.v1.CreateCategoryReq
	8,  // 9: admin.v1.Admin.UpdateCategory:input_type -> admin.v1.UpdateCategoryReq
	9,  // 10: admin.v1.Admin.DeleteCategory:input_type -> admin.v1.DeleteCategoryReq
	11, // 11: admin.v1.Admin.ListTags:input_type -> admin.v1.ListTagsReq
	13, // 12: admin.v1.Admin.CreateTag:input_type -> admin.v1.CreateTagReq
	14, // 13: admin.v1.Admin.UpdateTag:input_type -> admin.v1.UpdateTagReq
	15, // 14: admin.v1.Admin.DeleteTag:input_type -> admin.v1.DeleteTagReq
	17, // 15: admin.v1.Admin.TranslateBook:input_type -> admin.v1.TranslateBookReq
	19, // 16: admin.v1.Admin.TranslateBookChapters:input_type -> admin.v1.TranslateBookChaptersReq
	1,  // 17: admin.v1.Admin.GetStats:output_type -> admin.v1.GetStatsReply
	23, // 18: admin.v1.Admin.ListAuditLogs:output_type -> admin.v1.ListAuditLogsReply
	6,  // 19: admin.v1.Admin.ListCategories:output_type -> admin.v1.ListCategoriesReply
	4,  // 20: admin.v1.Admin.CreateCategory:output_type -> admin.v1.CategoryReply
	4,  // 21: admin.v1.Admin.UpdateCategory:output_type -> admin.v1.CategoryReply
	16, // 22: admin.v1.Admin.DeleteCategory:output_type -> admin.v1.EmptyReply
	12, // 23: admin.v1.Admin.ListTags:output_type -> admin.v1.ListTagsReply
	10, // 24: admin.v1.Admin.CreateTag:output_type -> admin.v1.TagReply
	10, // 25: admin.v1.Admin.UpdateTag:output_type -> admin.v1.TagReply
	16, // 26: admin.v1.Admin.DeleteTag:output_type -> admin.v1.EmptyReply
	18, // 27: admin.v1.Admin.TranslateBook:output_type -> admin.v1.TranslateBookReply
	20, // 28: admin.v1.Admin.TranslateBookChapters:output_type -> admin.v1.TranslateBookChaptersReply
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	file_admin_v1_admin_proto_msgTypes[8].OneofWrappers = []any{}
	file_admin_v1_admin_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
