// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: internal/conf/conf.proto

// 服务配置：http/grpc 端口、DB/Redis/OpenSearch 连接、JWT 密钥与有效期
// 全部支持环境变量覆盖（见 conf.go Load）

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpAddr      string                 `protobuf:"bytes,1,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"` // 缺省 :8000
	GrpcAddr      string                 `protobuf:"bytes,2,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"` // 缺省 :9000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *Server) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

type Data struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DbDsn          string                 `protobuf:"bytes,1,opt,name=db_dsn,json=dbDsn,proto3" json:"db_dsn,omitempty"`                            // 主库 DSN（env DB_DSN）
	DbDsnReplica   string                 `protobuf:"bytes,2,opt,name=db_dsn_replica,json=dbDsnReplica,proto3" json:"db_dsn_replica,omitempty"`     // 只读副本 DSN（env DB_DSN_REPLICA，可选）
	RedisAddr      string                 `protobuf:"bytes,3,opt,name=redis_addr,json=redisAddr,proto3" json:"redis_addr,omitempty"`                // env REDIS_ADDR
	OpensearchAddr string                 `protobuf:"bytes,4,opt,name=opensearch_addr,json=opensearchAddr,proto3" json:"opensearch_addr,omitempty"` // env OPENSEARCH_ADDR，可选
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDbDsn() string {
	if x != nil {
		return x.DbDsn
	}
	return ""
}

func (x *Data) GetDbDsnReplica() string {
	if x != nil {
		return x.DbDsnReplica
	}
	return ""
}

func (x *Data) GetRedisAddr() string {
	if x != nil {
		return x.RedisAddr
	}
	return ""
}

func (x *Data) GetOpensearchAddr() string {
	if x != nil {
		return x.OpensearchAddr
	}
	return ""
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtSecret     string                 `protobuf:"bytes,1,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`                // env JWT_SECRET
	JwtAccessTtl  int64                  `protobuf:"varint,2,opt,name=jwt_access_ttl,json=jwtAccessTtl,proto3" json:"jwt_access_ttl,omitempty"`    // access token 秒数，缺省 1800
	JwtRefreshTtl int64                  `protobuf:"varint,3,opt,name=jwt_refresh_ttl,json=jwtRefreshTtl,proto3" json:"jwt_refresh_ttl,omitempty"` // refresh token 秒数，缺省 604800
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

func (x *Auth) GetJwtAccessTtl() int64 {
	if x != nil {
		return x.JwtAccessTtl
	}
	return 0
}

func (x *Auth) GetJwtRefreshTtl() int64 {
	if x != nil {
		return x.JwtRefreshTtl
	}
	return 0
}

var File_internal_conf_conf_proto protoreflect.FileDescriptor

const file_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x18internal/conf/conf.proto\x12\x04conf\"q\n" +
	"\tBootstrap\x12$\n" +
	"\x06server\x18\x01 \x01(\v2\f.conf.ServerR\x06server\x12\x1e\n" +
	"\x04data\x18\x02 \x01(\v2\n" +
	".conf.DataR\x04data\x12\x1e\n" +
	"\x04auth\x18\x03 \x01(\v2\n" +
	".conf.AuthR\x04auth\"B\n" +
	"\x06Server\x12\x1b\n" +
	"\thttp_addr\x18\x01 \x01(\tR\bhttpAddr\x12\x1b\n" +
	"\tgrpc_addr\x18\x02 \x01(\tR\bgrpcAddr\"\x8b\x01\n" +
	"\x04Data\x12\x15\n" +
	"\x06db_dsn\x18\x01 \x01(\tR\x05dbDsn\x12$\n" +
	"\x0edb_dsn_replica\x18\x02 \x01(\tR\fdbDsnReplica\x12\x1d\n" +
	"\n" +
	"redis_addr\x18\x03 \x01(\tR\tredisAddr\x12'\n" +
	"\x0fopensearch_addr\x18\x04 \x01(\tR\x0eopensearchAddr\"s\n" +
	"\x04Auth\x12\x1d\n" +
	"\n" +
	"jwt_secret\x18\x01 \x01(\tR\tjwtSecret\x12$\n" +
	"\x0ejwt_access_ttl\x18\x02 \x01(\x03R\fjwtAccessTtl\x12&\n" +
	"\x0fjwt_refresh_ttl\x18\x03 \x01(\x03R\rjwtRefreshTtlB'Z%open-novel/backend/internal/conf;confb\x06proto3"

var (
	file_internal_conf_conf_proto_rawDescOnce sync.Once
	file_internal_conf_conf_proto_rawDescData []byte
)

func file_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)))
	})
	return file_internal_conf_conf_proto_rawDescData
}

var file_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil), // 0: conf.Bootstrap
	(*Server)(nil),    // 1: conf.Server
	(*Data)(nil),      // 2: conf.Data
	(*Auth)(nil),      // 3: conf.Auth
}
var file_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: conf.Bootstrap.server:type_name -> conf.Server
	2, // 1: conf.Bootstrap.data:type_name -> conf.Data
	3, // 2: conf.Bootstrap.auth:type_name -> conf.Auth
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_conf_conf_proto_init() }
func file_internal_conf_conf_proto_init() {
	if File_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_conf_proto = out.File
	file_internal_conf_conf_proto_goTypes = nil
	file_internal_conf_conf_proto_depIdxs = nil
}
