// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: api/recommendation/v1/recommendation.proto

// 推荐服务：热门/最新榜单（任务 #15）
// 业务码段 17xxxx；Phase 1 为 MySQL 榜单 stub，Phase 5 接入 AI 推荐（同一契约）

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Recommendation_GetRecommendations_FullMethodName = "/recommendation.v1.Recommendation/GetRecommendations"
)

// RecommendationClient is the client API for Recommendation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendationClient interface {
	// 推荐列表：strategy = hot | new（缺省 hot）；缓存 recommend:{strategy}:{page}:{page_size}
	GetRecommendations(ctx context.Context, in *GetRecommendationsReq, opts ...grpc.CallOption) (*GetRecommendationsReply, error)
}

type recommendationClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationClient(cc grpc.ClientConnInterface) RecommendationClient {
	return &recommendationClient{cc}
}

func (c *recommendationClient) GetRecommendations(ctx context.Context, in *GetRecommendationsReq, opts ...grpc.CallOption) (*GetRecommendationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationsReply)
	err := c.cc.Invoke(ctx, Recommendation_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServer is the server API for Recommendation service.
// All implementations must embed UnimplementedRecommendationServer
// for forward compatibility.
type RecommendationServer interface {
	// 推荐列表：strategy = hot | new（缺省 hot）；缓存 recommend:{strategy}:{page}:{page_size}
	GetRecommendations(context.Context, *GetRecommendationsReq) (*GetRecommendationsReply, error)
	mustEmbedUnimplementedRecommendationServer()
}

// UnimplementedRecommendationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationServer struct{}

func (UnimplementedRecommendationServer) GetRecommendations(context.Context, *GetRecommendationsReq) (*GetRecommendationsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedRecommendationServer) mustEmbedUnimplementedRecommendationServer() {}
func (UnimplementedRecommendationServer) testEmbeddedByValue()                        {}

// UnsafeRecommendationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationServer will
// result in compilation errors.
type UnsafeRecommendationServer interface {
	mustEmbedUnimplementedRecommendationServer()
}

func RegisterRecommendationServer(s grpc.ServiceRegistrar, srv RecommendationServer) {
	// If the following call panics, it indicates UnimplementedRecommendationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Recommendation_ServiceDesc, srv)
}

func _Recommendation_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recommendation_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServer).GetRecommendations(ctx, req.(*GetRecommendationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Recommendation_ServiceDesc is the grpc.ServiceDesc for Recommendation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recommendation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommendation.v1.Recommendation",
	HandlerType: (*RecommendationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendations",
			Handler:    _Recommendation_GetRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/recommendation/v1/recommendation.proto",
}
