// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: behavior/v1/behavior.proto

// 阅读行为分析服务：逐章阅读事件聚合（requireAdmin）
// REST 映射 GET /api/stats/behavior

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Behavior_GetBehaviorStats_FullMethodName = "/behavior.v1.Behavior/GetBehaviorStats"
)

// BehaviorClient is the client API for Behavior service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BehaviorClient interface {
	// 行为统计：热门阅读书籍 / 活跃读者 / 24 小时分布
	GetBehaviorStats(ctx context.Context, in *GetBehaviorStatsReq, opts ...grpc.CallOption) (*GetBehaviorStatsReply, error)
}

type behaviorClient struct {
	cc grpc.ClientConnInterface
}

func NewBehaviorClient(cc grpc.ClientConnInterface) BehaviorClient {
	return &behaviorClient{cc}
}

func (c *behaviorClient) GetBehaviorStats(ctx context.Context, in *GetBehaviorStatsReq, opts ...grpc.CallOption) (*GetBehaviorStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBehaviorStatsReply)
	err := c.cc.Invoke(ctx, Behavior_GetBehaviorStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BehaviorServer is the server API for Behavior service.
// All implementations must embed UnimplementedBehaviorServer
// for forward compatibility.
type BehaviorServer interface {
	// 行为统计：热门阅读书籍 / 活跃读者 / 24 小时分布
	GetBehaviorStats(context.Context, *GetBehaviorStatsReq) (*GetBehaviorStatsReply, error)
	mustEmbedUnimplementedBehaviorServer()
}

// UnimplementedBehaviorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBehaviorServer struct{}

func (UnimplementedBehaviorServer) GetBehaviorStats(context.Context, *GetBehaviorStatsReq) (*GetBehaviorStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBehaviorStats not implemented")
}
func (UnimplementedBehaviorServer) mustEmbedUnimplementedBehaviorServer() {}
func (UnimplementedBehaviorServer) testEmbeddedByValue()                  {}

// UnsafeBehaviorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BehaviorServer will
// result in compilation errors.
type UnsafeBehaviorServer interface {
	mustEmbedUnimplementedBehaviorServer()
}

func RegisterBehaviorServer(s grpc.ServiceRegistrar, srv BehaviorServer) {
	// If the following call panics, it indicates UnimplementedBehaviorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Behavior_ServiceDesc, srv)
}

func _Behavior_GetBehaviorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBehaviorStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BehaviorServer).GetBehaviorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Behavior_GetBehaviorStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BehaviorServer).GetBehaviorStats(ctx, req.(*GetBehaviorStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Behavior_ServiceDesc is the grpc.ServiceDesc for Behavior service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Behavior_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "behavior.v1.Behavior",
	HandlerType: (*BehaviorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBehaviorStats",
			Handler:    _Behavior_GetBehaviorStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "behavior/v1/behavior.proto",
}
