// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: behavior/v1/behavior.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBehaviorGetBehaviorStats = "/behavior.v1.Behavior/GetBehaviorStats"

type BehaviorHTTPServer interface {
	// GetBehaviorStats 行为统计：热门阅读书籍 / 活跃读者 / 24 小时分布
	GetBehaviorStats(context.Context, *GetBehaviorStatsReq) (*GetBehaviorStatsReply, error)
}

func RegisterBehaviorHTTPServer(s *http.Server, srv BehaviorHTTPServer) {
	r := s.Route("/")
	r.GET("/api/stats/behavior", _Behavior_GetBehaviorStats0_HTTP_Handler(srv))
}

func _Behavior_GetBehaviorStats0_HTTP_Handler(srv BehaviorHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBehaviorStatsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBehaviorGetBehaviorStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBehaviorStats(ctx, req.(*GetBehaviorStatsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBehaviorStatsReply)
		return ctx.Result(200, reply)
	}
}

type BehaviorHTTPClient interface {
	// GetBehaviorStats 行为统计：热门阅读书籍 / 活跃读者 / 24 小时分布
	GetBehaviorStats(ctx context.Context, req *GetBehaviorStatsReq, opts ...http.CallOption) (rsp *GetBehaviorStatsReply, err error)
}

type BehaviorHTTPClientImpl struct {
	cc *http.Client
}

func NewBehaviorHTTPClient(client *http.Client) BehaviorHTTPClient {
	return &BehaviorHTTPClientImpl{client}
}

// GetBehaviorStats 行为统计：热门阅读书籍 / 活跃读者 / 24 小时分布
func (c *BehaviorHTTPClientImpl) GetBehaviorStats(ctx context.Context, in *GetBehaviorStatsReq, opts ...http.CallOption) (*GetBehaviorStatsReply, error) {
	var out GetBehaviorStatsReply
	pattern := "/api/stats/behavior"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBehaviorGetBehaviorStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
