// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: chapter/v1/chapter.proto

// 章节服务：章节 / 正文 / 阅读进度 / 书架（任务 #16）
// 业务码段与通用共用 140xxx 标准码

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChapterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterNo     uint32                 `protobuf:"varint,2,opt,name=chapter_no,json=chapterNo,proto3" json:"chapter_no,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Lang          string                 `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"` // 缺省 zh-CN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterReq) Reset() {
	*x = CreateChapterReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterReq) ProtoMessage() {}

func (x *CreateChapterReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterReq.ProtoReflect.Descriptor instead.
func (*CreateChapterReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChapterReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *CreateChapterReq) GetChapterNo() uint32 {
	if x != nil {
		return x.ChapterNo
	}
	return 0
}

func (x *CreateChapterReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChapterReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateChapterReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type ChapterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        int64                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterNo     uint32                 `protobuf:"varint,3,opt,name=chapter_no,json=chapterNo,proto3" json:"chapter_no,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	WordCount     uint32                 `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	IsVip         int32                  `protobuf:"varint,6,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterReply) Reset() {
	*x = ChapterReply{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterReply) ProtoMessage() {}

func (x *ChapterReply) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterReply.ProtoReflect.Descriptor instead.
func (*ChapterReply) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{1}
}

func (x *ChapterReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChapterReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ChapterReply) GetChapterNo() uint32 {
	if x != nil {
		return x.ChapterNo
	}
	return 0
}

func (x *ChapterReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterReply) GetWordCount() uint32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ChapterReply) GetIsVip() int32 {
	if x != nil {
		return x.IsVip
	}
	return 0
}

func (x *ChapterReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChapterReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListChaptersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChaptersReq) Reset() {
	*x = ListChaptersReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChaptersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChaptersReq) ProtoMessage() {}

func (x *ListChaptersReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChaptersReq.ProtoReflect.Descriptor instead.
func (*ListChaptersReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{2}
}

func (x *ListChaptersReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ListChaptersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChaptersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListChaptersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ChapterReply        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChaptersReply) Reset() {
	*x = ListChaptersReply{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChaptersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChaptersReply) ProtoMessage() {}

func (x *ListChaptersReply) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChaptersReply.ProtoReflect.Descriptor instead.
func (*ListChaptersReply) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{3}
}

func (x *ListChaptersReply) GetList() []*ChapterReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListChaptersReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListChaptersReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChaptersReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetChapterContentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"` // 缺省 zh-CN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterContentReq) Reset() {
	*x = GetChapterContentReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterContentReq) ProtoMessage() {}

func (x *GetChapterContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterContentReq.ProtoReflect.Descriptor instead.
func (*GetChapterContentReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{4}
}

func (x *GetChapterContentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetChapterContentReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type ChapterContentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterContentReply) Reset() {
	*x = ChapterContentReply{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterContentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterContentReply) ProtoMessage() {}

func (x *ChapterContentReply) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterContentReply.ProtoReflect.Descriptor instead.
func (*ChapterContentReply) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{5}
}

func (x *ChapterContentReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChapterContentReply) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ChapterContentReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ChapterContentReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetReadingProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingProgressReq) Reset() {
	*x = GetReadingProgressReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingProgressReq) ProtoMessage() {}

func (x *GetReadingProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingProgressReq.ProtoReflect.Descriptor instead.
func (*GetReadingProgressReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{6}
}

func (x *GetReadingProgressReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type UpdateReadingProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Position      uint32                 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReadingProgressReq) Reset() {
	*x = UpdateReadingProgressReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReadingProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadingProgressReq) ProtoMessage() {}

func (x *UpdateReadingProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadingProgressReq.ProtoReflect.Descriptor instead.
func (*UpdateReadingProgressReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReadingProgressReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *UpdateReadingProgressReq) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *UpdateReadingProgressReq) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type ProgressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        int64                  `protobuf:"varint,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,4,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Position      uint32                 `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressReply) Reset() {
	*x = ProgressReply{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressReply) ProtoMessage() {}

func (x *ProgressReply) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressReply.ProtoReflect.Descriptor instead.
func (*ProgressReply) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgressReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProgressReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ProgressReply) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ProgressReply) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ProgressReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddToBookshelfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBookshelfReq) Reset() {
	*x = AddToBookshelfReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBookshelfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBookshelfReq) ProtoMessage() {}

func (x *AddToBookshelfReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBookshelfReq.ProtoReflect.Descriptor instead.
func (*AddToBookshelfReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{9}
}

func (x *AddToBookshelfReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type ShelfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        int64                  `protobuf:"varint,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShelfReply) Reset() {
	*x = ShelfReply{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShelfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShelfReply) ProtoMessage() {}

func (x *ShelfReply) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShelfReply.ProtoReflect.Descriptor instead.
func (*ShelfReply) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{10}
}

func (x *ShelfReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShelfReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShelfReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ShelfReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type RemoveFromBookshelfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBookshelfReq) Reset() {
	*x = RemoveFromBookshelfReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBookshelfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBookshelfReq) ProtoMessage() {}

func (x *RemoveFromBookshelfReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBookshelfReq.ProtoReflect.Descriptor instead.
func (*RemoveFromBookshelfReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveFromBookshelfReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type RemoveFromBookshelfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBookshelfReply) Reset() {
	*x = RemoveFromBookshelfReply{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBookshelfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBookshelfReply) ProtoMessage() {}

func (x *RemoveFromBookshelfReply) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBookshelfReply.ProtoReflect.Descriptor instead.
func (*RemoveFromBookshelfReply) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{12}
}

type ListBookshelfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookshelfReq) Reset() {
	*x = ListBookshelfReq{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookshelfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookshelfReq) ProtoMessage() {}

func (x *ListBookshelfReq) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookshelfReq.ProtoReflect.Descriptor instead.
func (*ListBookshelfReq) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{13}
}

func (x *ListBookshelfReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBookshelfReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBookshelfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ShelfReply          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookshelfReply) Reset() {
	*x = ListBookshelfReply{}
	mi := &file_chapter_v1_chapter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookshelfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookshelfReply) ProtoMessage() {}

func (x *ListBookshelfReply) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_v1_chapter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookshelfReply.ProtoReflect.Descriptor instead.
func (*ListBookshelfReply) Descriptor() ([]byte, []int) {
	return file_chapter_v1_chapter_proto_rawDescGZIP(), []int{14}
}

func (x *ListBookshelfReply) GetList() []*ShelfReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListBookshelfReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBookshelfReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBookshelfReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_chapter_v1_chapter_proto protoreflect.FileDescriptor

const file_chapter_v1_chapter_proto_rawDesc = "" +
	"\n" +
	"\x18chapter/v1/chapter.proto\x12\n" +
	"chapter.v1\x1a\x1cgoogle/api/annotations.proto\"\x8e\x01\n" +
	"\x10CreateChapterReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x1d\n" +
	"\n" +
	"chapter_no\x18\x02 \x01(\rR\tchapterNo\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\"\xd9\x01\n" +
	"\fChapterReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x03R\x06bookId\x12\x1d\n" +
	"\n" +
	"chapter_no\x18\x03 \x01(\rR\tchapterNo\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"word_count\x18\x05 \x01(\rR\twordCount\x12\x15\n" +
	"\x06is_vip\x18\x06 \x01(\x05R\x05isVip\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"[\n" +
	"\x0fListChaptersReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x88\x01\n" +
	"\x11ListChaptersReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.chapter.v1.ChapterReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\":\n" +
	"\x14GetChapterContentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"r\n" +
	"\x13ChapterContentReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03R\tchapterId\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"0\n" +
	"\x15GetReadingProgressReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"n\n" +
	"\x18UpdateReadingProgressReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03R\tchapterId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\rR\bposition\"\xab\x01\n" +
	"\rProgressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\x03R\x06bookId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x04 \x01(\x03R\tchapterId\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\rR\bposition\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\",\n" +
	"\x11AddToBookshelfReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"m\n" +
	"\n" +
	"ShelfReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\x03R\x06bookId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"1\n" +
	"\x16RemoveFromBookshelfReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"\x1a\n" +
	"\x18RemoveFromBookshelfReply\"C\n" +
	"\x10ListBookshelfReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x87\x01\n" +
	"\x12ListBookshelfReply\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.chapter.v1.ShelfReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xb1\a\n" +
	"\aChapter\x12t\n" +
	"\rCreateChapter\x12\x1c.chapter.v1.CreateChapterReq\x1a\x18.chapter.v1.ChapterReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/books/{book_id}/chapters\x12t\n" +
	"\fListChapters\x12\x1b.chapter.v1.ListChaptersReq\x1a\x1d.chapter.v1.ListChaptersReply\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/books/{book_id}/chapters\x12}\n" +
	"\x11GetChapterContent\x12 .chapter.v1.GetChapterContentReq\x1a\x1f.chapter.v1.ChapterContentReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/chapters/{id}/content\x12l\n" +
	"\x12GetReadingProgress\x12!.chapter.v1.GetReadingProgressReq\x1a\x19.chapter.v1.ProgressReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/progress\x12u\n" +
	"\x15UpdateReadingProgress\x12$.chapter.v1.UpdateReadingProgressReq\x1a\x19.chapter.v1.ProgressReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/api/v1/progress\x12e\n" +
	"\x0eAddToBookshelf\x12\x1d.chapter.v1.AddToBookshelfReq\x1a\x16.chapter.v1.ShelfReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/bookshelf\x12\x84\x01\n" +
	"\x13RemoveFromBookshelf\x12\".chapter.v1.RemoveFromBookshelfReq\x1a$.chapter.v1.RemoveFromBookshelfReply\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/api/v1/bookshelf/{book_id}\x12h\n" +
	"\rListBookshelf\x12\x1c.chapter.v1.ListBookshelfReq\x1a\x1e.chapter.v1.ListBookshelfReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/bookshelfB&Z$open-novel/backend/api/chapter/v1;v1b\x06proto3"

var (
	file_chapter_v1_chapter_proto_rawDescOnce sync.Once
	file_chapter_v1_chapter_proto_rawDescData []byte
)

func file_chapter_v1_chapter_proto_rawDescGZIP() []byte {
	file_chapter_v1_chapter_proto_rawDescOnce.Do(func() {
		file_chapter_v1_chapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chapter_v1_chapter_proto_rawDesc), len(file_chapter_v1_chapter_proto_rawDesc)))
	})
	return file_chapter_v1_chapter_proto_rawDescData
}

var file_chapter_v1_chapter_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_chapter_v1_chapter_proto_goTypes = []any{
	(*CreateChapterReq)(nil),         // 0: chapter.v1.CreateChapterReq
	(*ChapterReply)(nil),             // 1: chapter.v1.ChapterReply
	(*ListChaptersReq)(nil),          // 2: chapter.v1.ListChaptersReq
	(*ListChaptersReply)(nil),        // 3: chapter.v1.ListChaptersReply
	(*GetChapterContentReq)(nil),     // 4: chapter.v1.GetChapterContentReq
	(*ChapterContentReply)(nil),      // 5: chapter.v1.ChapterContentReply
	(*GetReadingProgressReq)(nil),    // 6: chapter.v1.GetReadingProgressReq
	(*UpdateReadingProgressReq)(nil), // 7: chapter.v1.UpdateReadingProgressReq
	(*ProgressReply)(nil),            // 8: chapter.v1.ProgressReply
	(*AddToBookshelfReq)(nil),        // 9: chapter.v1.AddToBookshelfReq
	(*ShelfReply)(nil),               // 10: chapter.v1.ShelfReply
	(*RemoveFromBookshelfReq)(nil),   // 11: chapter.v1.RemoveFromBookshelfReq
	(*RemoveFromBookshelfReply)(nil), // 12: chapter.v1.RemoveFromBookshelfReply
	(*ListBookshelfReq)(nil),         // 13: chapter.v1.ListBookshelfReq
	(*ListBookshelfReply)(nil),       // 14: chapter.v1.ListBookshelfReply
}
var file_chapter_v1_chapter_proto_depIdxs = []int32{
	1,  // 0: chapter.v1.ListChaptersReply.list:type_name -> chapter.v1.ChapterReply
	10, // 1: chapter.v1.ListBookshelfReply.list:type_name -> chapter.v1.ShelfReply
	0,  // 2: chapter.v1.Chapter.CreateChapter:input_type -> chapter.v1.CreateChapterReq
	2,  // 3: chapter.v1.Chapter.ListChapters:input_type -> chapter.v1.ListChaptersReq
	4,  // 4: chapter.v1.Chapter.GetChapterContent:input_type -> chapter.v1.GetChapterContentReq
	6,  // 5: chapter.v1.Chapter.GetReadingProgress:input_type -> chapter.v1.GetReadingProgressReq
	7,  // 6: chapter.v1.Chapter.UpdateReadingProgress:input_type -> chapter.v1.UpdateReadingProgressReq
	9,  // 7: chapter.v1.Chapter.AddToBookshelf:input_type -> chapter.v1.AddToBookshelfReq
	11, // 8: chapter.v1.Chapter.RemoveFromBookshelf:input_type -> chapter.v1.RemoveFromBookshelfReq
	13, // 9: chapter.v1.Chapter.ListBookshelf:input_type -> chapter.v1.ListBookshelfReq
	1,  // 10: chapter.v1.Chapter.CreateChapter:output_type -> chapter.v1.ChapterReply
	3,  // 11: chapter.v1.Chapter.ListChapters:output_type -> chapter.v1.ListChaptersReply
	5,  // 12: chapter.v1.Chapter.GetChapterContent:output_type -> chapter.v1.ChapterContentReply
	8,  // 13: chapter.v1.Chapter.GetReadingProgress:output_type -> chapter.v1.ProgressReply
	8,  // 14: chapter.v1.Chapter.UpdateReadingProgress:output_type -> chapter.v1.ProgressReply
	10, // 15: chapter.v1.Chapter.AddToBookshelf:output_type -> chapter.v1.ShelfReply
	12, // 16: chapter.v1.Chapter.RemoveFromBookshelf:output_type -> chapter.v1.RemoveFromBookshelfReply
	14, // 17: chapter.v1.Chapter.ListBookshelf:output_type -> chapter.v1.ListBookshelfReply
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_chapter_v1_chapter_proto_init() }
func file_chapter_v1_chapter_proto_init() {
	if File_chapter_v1_chapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chapter_v1_chapter_proto_rawDesc), len(file_chapter_v1_chapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chapter_v1_chapter_proto_goTypes,
		DependencyIndexes: file_chapter_v1_chapter_proto_depIdxs,
		MessageInfos:      file_chapter_v1_chapter_proto_msgTypes,
	}.Build()
	File_chapter_v1_chapter_proto = out.File
	file_chapter_v1_chapter_proto_goTypes = nil
	file_chapter_v1_chapter_proto_depIdxs = nil
}
