// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: api/chapter/v1/chapter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChapterAddToBookshelf = "/chapter.v1.Chapter/AddToBookshelf"
const OperationChapterCreateChapter = "/chapter.v1.Chapter/CreateChapter"
const OperationChapterGetChapterContent = "/chapter.v1.Chapter/GetChapterContent"
const OperationChapterGetReadingProgress = "/chapter.v1.Chapter/GetReadingProgress"
const OperationChapterListBookshelf = "/chapter.v1.Chapter/ListBookshelf"
const OperationChapterListChapters = "/chapter.v1.Chapter/ListChapters"
const OperationChapterRemoveFromBookshelf = "/chapter.v1.Chapter/RemoveFromBookshelf"
const OperationChapterUpdateReadingProgress = "/chapter.v1.Chapter/UpdateReadingProgress"

type ChapterHTTPServer interface {
	AddToBookshelf(context.Context, *AddToBookshelfReq) (*ShelfReply, error)
	// CreateChapter 新建章节（需登录；章节 + 正文同事务，按 rune 计数）
	CreateChapter(context.Context, *CreateChapterReq) (*ChapterReply, error)
	// GetChapterContent 正文（缓存 chapter:content:{book_id}:{chapter_id}:{lang}）
	GetChapterContent(context.Context, *GetChapterContentReq) (*ChapterContentReply, error)
	GetReadingProgress(context.Context, *GetReadingProgressReq) (*ProgressReply, error)
	ListBookshelf(context.Context, *ListBookshelfReq) (*ListBookshelfReply, error)
	// ListChapters 章节列表（缓存 chapter:list:{book_id}:{page}:{page_size}）
	ListChapters(context.Context, *ListChaptersReq) (*ListChaptersReply, error)
	RemoveFromBookshelf(context.Context, *RemoveFromBookshelfReq) (*RemoveFromBookshelfReply, error)
	UpdateReadingProgress(context.Context, *UpdateReadingProgressReq) (*ProgressReply, error)
}

func RegisterChapterHTTPServer(s *http.Server, srv ChapterHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/books/{book_id}/chapters", _Chapter_CreateChapter0_HTTP_Handler(srv))
	r.GET("/api/v1/books/{book_id}/chapters", _Chapter_ListChapters0_HTTP_Handler(srv))
	r.GET("/api/v1/chapters/{id}/content", _Chapter_GetChapterContent0_HTTP_Handler(srv))
	r.GET("/api/v1/progress", _Chapter_GetReadingProgress0_HTTP_Handler(srv))
	r.PUT("/api/v1/progress", _Chapter_UpdateReadingProgress0_HTTP_Handler(srv))
	r.POST("/api/v1/bookshelf", _Chapter_AddToBookshelf0_HTTP_Handler(srv))
	r.DELETE("/api/v1/bookshelf/{book_id}", _Chapter_RemoveFromBookshelf0_HTTP_Handler(srv))
	r.GET("/api/v1/bookshelf", _Chapter_ListBookshelf0_HTTP_Handler(srv))
}

func _Chapter_CreateChapter0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateChapterReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterCreateChapter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateChapter(ctx, req.(*CreateChapterReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChapterReply)
		return ctx.Result(200, reply)
	}
}

func _Chapter_ListChapters0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListChaptersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterListChapters)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChapters(ctx, req.(*ListChaptersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListChaptersReply)
		return ctx.Result(200, reply)
	}
}

func _Chapter_GetChapterContent0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChapterContentReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterGetChapterContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChapterContent(ctx, req.(*GetChapterContentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChapterContentReply)
		return ctx.Result(200, reply)
	}
}

func _Chapter_GetReadingProgress0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReadingProgressReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterGetReadingProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReadingProgress(ctx, req.(*GetReadingProgressReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProgressReply)
		return ctx.Result(200, reply)
	}
}

func _Chapter_UpdateReadingProgress0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateReadingProgressReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterUpdateReadingProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateReadingProgress(ctx, req.(*UpdateReadingProgressReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProgressReply)
		return ctx.Result(200, reply)
	}
}

func _Chapter_AddToBookshelf0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddToBookshelfReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterAddToBookshelf)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddToBookshelf(ctx, req.(*AddToBookshelfReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShelfReply)
		return ctx.Result(200, reply)
	}
}

func _Chapter_RemoveFromBookshelf0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveFromBookshelfReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterRemoveFromBookshelf)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveFromBookshelf(ctx, req.(*RemoveFromBookshelfReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveFromBookshelfReply)
		return ctx.Result(200, reply)
	}
}

func _Chapter_ListBookshelf0_HTTP_Handler(srv ChapterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBookshelfReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChapterListBookshelf)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBookshelf(ctx, req.(*ListBookshelfReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBookshelfReply)
		return ctx.Result(200, reply)
	}
}

type ChapterHTTPClient interface {
	AddToBookshelf(ctx context.Context, req *AddToBookshelfReq, opts ...http.CallOption) (rsp *ShelfReply, err error)
	// CreateChapter 新建章节（需登录；章节 + 正文同事务，按 rune 计数）
	CreateChapter(ctx context.Context, req *CreateChapterReq, opts ...http.CallOption) (rsp *ChapterReply, err error)
	// GetChapterContent 正文（缓存 chapter:content:{book_id}:{chapter_id}:{lang}）
	GetChapterContent(ctx context.Context, req *GetChapterContentReq, opts ...http.CallOption) (rsp *ChapterContentReply, err error)
	GetReadingProgress(ctx context.Context, req *GetReadingProgressReq, opts ...http.CallOption) (rsp *ProgressReply, err error)
	ListBookshelf(ctx context.Context, req *ListBookshelfReq, opts ...http.CallOption) (rsp *ListBookshelfReply, err error)
	// ListChapters 章节列表（缓存 chapter:list:{book_id}:{page}:{page_size}）
	ListChapters(ctx context.Context, req *ListChaptersReq, opts ...http.CallOption) (rsp *ListChaptersReply, err error)
	RemoveFromBookshelf(ctx context.Context, req *RemoveFromBookshelfReq, opts ...http.CallOption) (rsp *RemoveFromBookshelfReply, err error)
	UpdateReadingProgress(ctx context.Context, req *UpdateReadingProgressReq, opts ...http.CallOption) (rsp *ProgressReply, err error)
}

type ChapterHTTPClientImpl struct {
	cc *http.Client
}

func NewChapterHTTPClient(client *http.Client) ChapterHTTPClient {
	return &ChapterHTTPClientImpl{client}
}

func (c *ChapterHTTPClientImpl) AddToBookshelf(ctx context.Context, in *AddToBookshelfReq, opts ...http.CallOption) (*ShelfReply, error) {
	var out ShelfReply
	pattern := "/api/v1/bookshelf"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChapterAddToBookshelf))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateChapter 新建章节（需登录；章节 + 正文同事务，按 rune 计数）
func (c *ChapterHTTPClientImpl) CreateChapter(ctx context.Context, in *CreateChapterReq, opts ...http.CallOption) (*ChapterReply, error) {
	var out ChapterReply
	pattern := "/api/v1/books/{book_id}/chapters"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChapterCreateChapter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetChapterContent 正文（缓存 chapter:content:{book_id}:{chapter_id}:{lang}）
func (c *ChapterHTTPClientImpl) GetChapterContent(ctx context.Context, in *GetChapterContentReq, opts ...http.CallOption) (*ChapterContentReply, error) {
	var out ChapterContentReply
	pattern := "/api/v1/chapters/{id}/content"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChapterGetChapterContent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChapterHTTPClientImpl) GetReadingProgress(ctx context.Context, in *GetReadingProgressReq, opts ...http.CallOption) (*ProgressReply, error) {
	var out ProgressReply
	pattern := "/api/v1/progress"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChapterGetReadingProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChapterHTTPClientImpl) ListBookshelf(ctx context.Context, in *ListBookshelfReq, opts ...http.CallOption) (*ListBookshelfReply, error) {
	var out ListBookshelfReply
	pattern := "/api/v1/bookshelf"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChapterListBookshelf))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChapters 章节列表（缓存 chapter:list:{book_id}:{page}:{page_size}）
func (c *ChapterHTTPClientImpl) ListChapters(ctx context.Context, in *ListChaptersReq, opts ...http.CallOption) (*ListChaptersReply, error) {
	var out ListChaptersReply
	pattern := "/api/v1/books/{book_id}/chapters"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChapterListChapters))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChapterHTTPClientImpl) RemoveFromBookshelf(ctx context.Context, in *RemoveFromBookshelfReq, opts ...http.CallOption) (*RemoveFromBookshelfReply, error) {
	var out RemoveFromBookshelfReply
	pattern := "/api/v1/bookshelf/{book_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChapterRemoveFromBookshelf))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ChapterHTTPClientImpl) UpdateReadingProgress(ctx context.Context, in *UpdateReadingProgressReq, opts ...http.CallOption) (*ProgressReply, error) {
	var out ProgressReply
	pattern := "/api/v1/progress"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChapterUpdateReadingProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
