// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: book/v1/book.proto

// 书籍服务：元数据 / 分页列表 / 分类标签 / 多语言翻译（任务 #18）
// 业务码段 12xxxx；GetBook 走缓存链 book:{id}:{lang}（§三.2 / §五）

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"` // 空 = 原语言
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookReq) Reset() {
	*x = GetBookReq{}
	mi := &file_book_v1_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookReq) ProtoMessage() {}

func (x *GetBookReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookReq.ProtoReflect.Descriptor instead.
func (*GetBookReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBookReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type BookReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	IsVip         int32                  `protobuf:"varint,7,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookReply) Reset() {
	*x = BookReply{}
	mi := &file_book_v1_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookReply) ProtoMessage() {}

func (x *BookReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookReply.ProtoReflect.Descriptor instead.
func (*BookReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *BookReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookReply) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookReply) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *BookReply) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *BookReply) GetIsVip() int32 {
	if x != nil {
		return x.IsVip
	}
	return 0
}

func (x *BookReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListBooksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagId         int64                  `protobuf:"varint,5,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` // 0 = 不过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksReq) Reset() {
	*x = ListBooksReq{}
	mi := &file_book_v1_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksReq) ProtoMessage() {}

func (x *ListBooksReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksReq.ProtoReflect.Descriptor instead.
func (*ListBooksReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{2}
}

func (x *ListBooksReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBooksReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBooksReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ListBooksReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListBooksReq) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *ListBooksReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListBooksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BookReply           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksReply) Reset() {
	*x = ListBooksReply{}
	mi := &file_book_v1_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksReply) ProtoMessage() {}

func (x *ListBooksReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksReply.ProtoReflect.Descriptor instead.
func (*ListBooksReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{3}
}

func (x *ListBooksReply) GetList() []*BookReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListBooksReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBooksReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBooksReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateBookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Lang          string                 `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"` // 缺省 zh-CN
	IsVip         int32                  `protobuf:"varint,6,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	CategoryIds   []int64                `protobuf:"varint,7,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	TagIds        []int64                `protobuf:"varint,8,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	Translations  []*TranslationReq      `protobuf:"bytes,9,rep,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookReq) Reset() {
	*x = CreateBookReq{}
	mi := &file_book_v1_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookReq) ProtoMessage() {}

func (x *CreateBookReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookReq.ProtoReflect.Descriptor instead.
func (*CreateBookReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBookReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateBookReq) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateBookReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreateBookReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *CreateBookReq) GetIsVip() int32 {
	if x != nil {
		return x.IsVip
	}
	return 0
}

func (x *CreateBookReq) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *CreateBookReq) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *CreateBookReq) GetTranslations() []*TranslationReq {
	if x != nil {
		return x.Translations
	}
	return nil
}

type TranslationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationReq) Reset() {
	*x = TranslationReq{}
	mi := &file_book_v1_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationReq) ProtoMessage() {}

func (x *TranslationReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationReq.ProtoReflect.Descriptor instead.
func (*TranslationReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{5}
}

func (x *TranslationReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TranslationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TranslationReq) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TranslationReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

type CreateBookReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookReply) Reset() {
	*x = CreateBookReply{}
	mi := &file_book_v1_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookReply) ProtoMessage() {}

func (x *CreateBookReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookReply.ProtoReflect.Descriptor instead.
func (*CreateBookReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBookReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateBookReply) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateBookReply) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type UpsertBookTranslationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertBookTranslationReq) Reset() {
	*x = UpsertBookTranslationReq{}
	mi := &file_book_v1_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertBookTranslationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBookTranslationReq) ProtoMessage() {}

func (x *UpsertBookTranslationReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBookTranslationReq.ProtoReflect.Descriptor instead.
func (*UpsertBookTranslationReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertBookTranslationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertBookTranslationReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *UpsertBookTranslationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpsertBookTranslationReq) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpsertBookTranslationReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

type UpsertBookTranslationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertBookTranslationReply) Reset() {
	*x = UpsertBookTranslationReply{}
	mi := &file_book_v1_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertBookTranslationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBookTranslationReply) ProtoMessage() {}

func (x *UpsertBookTranslationReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBookTranslationReply.ProtoReflect.Descriptor instead.
func (*UpsertBookTranslationReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertBookTranslationReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *UpsertBookTranslationReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type UpdateBookStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 1 上架 0 下架
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookStatusReq) Reset() {
	*x = UpdateBookStatusReq{}
	mi := &file_book_v1_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookStatusReq) ProtoMessage() {}

func (x *UpdateBookStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateBookStatusReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBookStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBookStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_book_v1_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{10}
}

type ListCategoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesReq) Reset() {
	*x = ListCategoriesReq{}
	mi := &file_book_v1_book_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesReq) ProtoMessage() {}

func (x *ListCategoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesReq.ProtoReflect.Descriptor instead.
func (*ListCategoriesReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{11}
}

type CategoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryReply) Reset() {
	*x = CategoryReply{}
	mi := &file_book_v1_book_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryReply) ProtoMessage() {}

func (x *CategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryReply.ProtoReflect.Descriptor instead.
func (*CategoryReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{12}
}

func (x *CategoryReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ListCategoriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CategoryReply       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesReply) Reset() {
	*x = ListCategoriesReply{}
	mi := &file_book_v1_book_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesReply) ProtoMessage() {}

func (x *ListCategoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesReply.ProtoReflect.Descriptor instead.
func (*ListCategoriesReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{13}
}

func (x *ListCategoriesReply) GetList() []*CategoryReply {
	if x != nil {
		return x.List
	}
	return nil
}

type ListTagsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsReq) Reset() {
	*x = ListTagsReq{}
	mi := &file_book_v1_book_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsReq) ProtoMessage() {}

func (x *ListTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsReq.ProtoReflect.Descriptor instead.
func (*ListTagsReq) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{14}
}

func (x *ListTagsReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type TagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagReply) Reset() {
	*x = TagReply{}
	mi := &file_book_v1_book_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagReply) ProtoMessage() {}

func (x *TagReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagReply.ProtoReflect.Descriptor instead.
func (*TagReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{15}
}

func (x *TagReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type ListTagsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TagReply            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsReply) Reset() {
	*x = ListTagsReply{}
	mi := &file_book_v1_book_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsReply) ProtoMessage() {}

func (x *ListTagsReply) ProtoReflect() protoreflect.Message {
	mi := &file_book_v1_book_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsReply.ProtoReflect.Descriptor instead.
func (*ListTagsReply) Descriptor() ([]byte, []int) {
	return file_book_v1_book_proto_rawDescGZIP(), []int{16}
}

func (x *ListTagsReply) GetList() []*TagReply {
	if x != nil {
		return x.List
	}
	return nil
}

var File_book_v1_book_proto protoreflect.FileDescriptor

const file_book_v1_book_proto_rawDesc = "" +
	"\n" +
	"\x12book/v1/book.proto\x12\abook.v1\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\n" +
	"GetBookReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"\xbc\x01\n" +
	"\tBookReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\x12\x15\n" +
	"\x06is_vip\x18\a \x01(\x05R\x05isVip\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"\xa3\x01\n" +
	"\fListBooksReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x15\n" +
	"\x06tag_id\x18\x05 \x01(\x03R\x05tagId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\x7f\n" +
	"\x0eListBooksReply\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.book.v1.BookReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x91\x02\n" +
	"\rCreateBookReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\x12\x15\n" +
	"\x06is_vip\x18\x06 \x01(\x05R\x05isVip\x12!\n" +
	"\fcategory_ids\x18\a \x03(\x03R\vcategoryIds\x12\x17\n" +
	"\atag_ids\x18\b \x03(\x03R\x06tagIds\x12;\n" +
	"\ftranslations\x18\t \x03(\v2\x17.book.v1.TranslationReqR\ftranslations\"j\n" +
	"\x0eTranslationReq\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\"M\n" +
	"\x0fCreateBookReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"\x84\x01\n" +
	"\x18UpsertBookTranslationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\"I\n" +
	"\x1aUpsertBookTranslationReply\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"=\n" +
	"\x13UpdateBookStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\f\n" +
	"\n" +
	"EmptyReply\"\x13\n" +
	"\x11ListCategoriesReq\"P\n" +
	"\rCategoryReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\"A\n" +
	"\x13ListCategoriesReply\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.book.v1.CategoryReplyR\x04list\"!\n" +
	"\vListTagsReq\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\"B\n" +
	"\bTagReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\"6\n" +
	"\rListTagsReply\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.book.v1.TagReplyR\x04list2\xa1\x05\n" +
	"\x04Book\x12K\n" +
	"\aGetBook\x12\x13.book.v1.GetBookReq\x1a\x12.book.v1.BookReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/books/{id}\x12O\n" +
	"\tListBooks\x12\x15.book.v1.ListBooksReq\x1a\x17.book.v1.ListBooksReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/books\x12U\n" +
	"\n" +
	"CreateBook\x12\x16.book.v1.CreateBookReq\x1a\x18.book.v1.CreateBookReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/books\x12\x87\x01\n" +
	"\x15UpsertBookTranslation\x12!.book.v1.UpsertBookTranslationReq\x1a#.book.v1.UpsertBookTranslationReply\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/api/books/{id}/translation\x12c\n" +
	"\x0eListCategories\x12\x1a.book.v1.ListCategoriesReq\x1a\x1c.book.v1.ListCategoriesReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/categories\x12h\n" +
	"\x10UpdateBookStatus\x12\x1c.book.v1.UpdateBookStatusReq\x1a\x13.book.v1.EmptyReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*2\x16/api/books/{id}/status\x12K\n" +
	"\bListTags\x12\x14.book.v1.ListTagsReq\x1a\x16.book.v1.ListTagsReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/tagsB#Z!open-novel/backend/api/book/v1;v1b\x06proto3"

var (
	file_book_v1_book_proto_rawDescOnce sync.Once
	file_book_v1_book_proto_rawDescData []byte
)

func file_book_v1_book_proto_rawDescGZIP() []byte {
	file_book_v1_book_proto_rawDescOnce.Do(func() {
		file_book_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_v1_book_proto_rawDesc), len(file_book_v1_book_proto_rawDesc)))
	})
	return file_book_v1_book_proto_rawDescData
}

var file_book_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_book_v1_book_proto_goTypes = []any{
	(*GetBookReq)(nil),                 // 0: book.v1.GetBookReq
	(*BookReply)(nil),                  // 1: book.v1.BookReply
	(*ListBooksReq)(nil),               // 2: book.v1.ListBooksReq
	(*ListBooksReply)(nil),             // 3: book.v1.ListBooksReply
	(*CreateBookReq)(nil),              // 4: book.v1.CreateBookReq
	(*TranslationReq)(nil),             // 5: book.v1.TranslationReq
	(*CreateBookReply)(nil),            // 6: book.v1.CreateBookReply
	(*UpsertBookTranslationReq)(nil),   // 7: book.v1.UpsertBookTranslationReq
	(*UpsertBookTranslationReply)(nil), // 8: book.v1.UpsertBookTranslationReply
	(*UpdateBookStatusReq)(nil),        // 9: book.v1.UpdateBookStatusReq
	(*EmptyReply)(nil),                 // 10: book.v1.EmptyReply
	(*ListCategoriesReq)(nil),          // 11: book.v1.ListCategoriesReq
	(*CategoryReply)(nil),              // 12: book.v1.CategoryReply
	(*ListCategoriesReply)(nil),        // 13: book.v1.ListCategoriesReply
	(*ListTagsReq)(nil),                // 14: book.v1.ListTagsReq
	(*TagReply)(nil),                   // 15: book.v1.TagReply
	(*ListTagsReply)(nil),              // 16: book.v1.ListTagsReply
}
var file_book_v1_book_proto_depIdxs = []int32{
	1,  // 0: book.v1.ListBooksReply.list:type_name -> book.v1.BookReply
	5,  // 1: book.v1.CreateBookReq.translations:type_name -> book.v1.TranslationReq
	12, // 2: book.v1.ListCategoriesReply.list:type_name -> book.v1.CategoryReply
	15, // 3: book.v1.ListTagsReply.list:type_name -> book.v1.TagReply
	0,  // 4: book.v1.Book.GetBook:input_type -> book.v1.GetBookReq
	2,  // 5: book.v1.Book.ListBooks:input_type -> book.v1.ListBooksReq
	4,  // 6: book.v1.Book.CreateBook:input_type -> book.v1.CreateBookReq
	7,  // 7: book.v1.Book.UpsertBookTranslation:input_type -> book.v1.UpsertBookTranslationReq
	11, // 8: book.v1.Book.ListCategories:input_type -> book.v1.ListCategoriesReq
	9,  // 9: book.v1.Book.UpdateBookStatus:input_type -> book.v1.UpdateBookStatusReq
	14, // 10: book.v1.Book.ListTags:input_type -> book.v1.ListTagsReq
	1,  // 11: book.v1.Book.GetBook:output_type -> book.v1.BookReply
	3,  // 12: book.v1.Book.ListBooks:output_type -> book.v1.ListBooksReply
	6,  // 13: book.v1.Book.CreateBook:output_type -> book.v1.CreateBookReply
	8,  // 14: book.v1.Book.UpsertBookTranslation:output_type -> book.v1.UpsertBookTranslationReply
	13, // 15: book.v1.Book.ListCategories:output_type -> book.v1.ListCategoriesReply
	10, // 16: book.v1.Book.UpdateBookStatus:output_type -> book.v1.EmptyReply
	16, // 17: book.v1.Book.ListTags:output_type -> book.v1.ListTagsReply
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_book_v1_book_proto_init() }
func file_book_v1_book_proto_init() {
	if File_book_v1_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_v1_book_proto_rawDesc), len(file_book_v1_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_v1_book_proto_goTypes,
		DependencyIndexes: file_book_v1_book_proto_depIdxs,
		MessageInfos:      file_book_v1_book_proto_msgTypes,
	}.Build()
	File_book_v1_book_proto = out.File
	file_book_v1_book_proto_goTypes = nil
	file_book_v1_book_proto_depIdxs = nil
}
