// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: cdn/v1/cdn.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCdnCreateProvider = "/cdn.v1.Cdn/CreateProvider"
const OperationCdnDeleteProvider = "/cdn.v1.Cdn/DeleteProvider"
const OperationCdnListProviders = "/cdn.v1.Cdn/ListProviders"
const OperationCdnToggleProvider = "/cdn.v1.Cdn/ToggleProvider"
const OperationCdnUpdateProvider = "/cdn.v1.Cdn/UpdateProvider"

type CdnHTTPServer interface {
	// CreateProvider 新建厂商：code ∈ cloudflare/cloudfront/aliyun/tencent；enabled 固定为 1
	CreateProvider(context.Context, *CreateProviderReq) (*ProviderReply, error)
	// DeleteProvider 删除厂商（先禁用再删）
	DeleteProvider(context.Context, *DeleteProviderReq) (*EmptyReply, error)
	// ListProviders 厂商列表（含禁用），sort 升序
	ListProviders(context.Context, *ListProvidersReq) (*ListProvidersReply, error)
	// ToggleProvider 启停厂商（灰度回滚手段：enabled=0 即摘除）
	ToggleProvider(context.Context, *ToggleProviderReq) (*ProviderReply, error)
	// UpdateProvider 更新厂商；config 传入字段重加密合并，空值保留原值
	UpdateProvider(context.Context, *UpdateProviderReq) (*ProviderReply, error)
}

func RegisterCdnHTTPServer(s *http.Server, srv CdnHTTPServer) {
	r := s.Route("/")
	r.GET("/api/cdn/admin/providers", _Cdn_ListProviders0_HTTP_Handler(srv))
	r.POST("/api/cdn/admin/providers", _Cdn_CreateProvider0_HTTP_Handler(srv))
	r.PUT("/api/cdn/admin/providers/{id}", _Cdn_UpdateProvider0_HTTP_Handler(srv))
	r.DELETE("/api/cdn/admin/providers/{id}", _Cdn_DeleteProvider0_HTTP_Handler(srv))
	r.PATCH("/api/cdn/admin/providers/{id}/toggle", _Cdn_ToggleProvider0_HTTP_Handler(srv))
}

func _Cdn_ListProviders0_HTTP_Handler(srv CdnHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProvidersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCdnListProviders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProviders(ctx, req.(*ListProvidersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProvidersReply)
		return ctx.Result(200, reply)
	}
}

func _Cdn_CreateProvider0_HTTP_Handler(srv CdnHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProviderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCdnCreateProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProvider(ctx, req.(*CreateProviderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProviderReply)
		return ctx.Result(200, reply)
	}
}

func _Cdn_UpdateProvider0_HTTP_Handler(srv CdnHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProviderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCdnUpdateProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProvider(ctx, req.(*UpdateProviderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProviderReply)
		return ctx.Result(200, reply)
	}
}

func _Cdn_DeleteProvider0_HTTP_Handler(srv CdnHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProviderReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCdnDeleteProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProvider(ctx, req.(*DeleteProviderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Cdn_ToggleProvider0_HTTP_Handler(srv CdnHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ToggleProviderReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCdnToggleProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleProvider(ctx, req.(*ToggleProviderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProviderReply)
		return ctx.Result(200, reply)
	}
}

type CdnHTTPClient interface {
	// CreateProvider 新建厂商：code ∈ cloudflare/cloudfront/aliyun/tencent；enabled 固定为 1
	CreateProvider(ctx context.Context, req *CreateProviderReq, opts ...http.CallOption) (rsp *ProviderReply, err error)
	// DeleteProvider 删除厂商（先禁用再删）
	DeleteProvider(ctx context.Context, req *DeleteProviderReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// ListProviders 厂商列表（含禁用），sort 升序
	ListProviders(ctx context.Context, req *ListProvidersReq, opts ...http.CallOption) (rsp *ListProvidersReply, err error)
	// ToggleProvider 启停厂商（灰度回滚手段：enabled=0 即摘除）
	ToggleProvider(ctx context.Context, req *ToggleProviderReq, opts ...http.CallOption) (rsp *ProviderReply, err error)
	// UpdateProvider 更新厂商；config 传入字段重加密合并，空值保留原值
	UpdateProvider(ctx context.Context, req *UpdateProviderReq, opts ...http.CallOption) (rsp *ProviderReply, err error)
}

type CdnHTTPClientImpl struct {
	cc *http.Client
}

func NewCdnHTTPClient(client *http.Client) CdnHTTPClient {
	return &CdnHTTPClientImpl{client}
}

// CreateProvider 新建厂商：code ∈ cloudflare/cloudfront/aliyun/tencent；enabled 固定为 1
func (c *CdnHTTPClientImpl) CreateProvider(ctx context.Context, in *CreateProviderReq, opts ...http.CallOption) (*ProviderReply, error) {
	var out ProviderReply
	pattern := "/api/cdn/admin/providers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCdnCreateProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteProvider 删除厂商（先禁用再删）
func (c *CdnHTTPClientImpl) DeleteProvider(ctx context.Context, in *DeleteProviderReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/cdn/admin/providers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCdnDeleteProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProviders 厂商列表（含禁用），sort 升序
func (c *CdnHTTPClientImpl) ListProviders(ctx context.Context, in *ListProvidersReq, opts ...http.CallOption) (*ListProvidersReply, error) {
	var out ListProvidersReply
	pattern := "/api/cdn/admin/providers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCdnListProviders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleProvider 启停厂商（灰度回滚手段：enabled=0 即摘除）
func (c *CdnHTTPClientImpl) ToggleProvider(ctx context.Context, in *ToggleProviderReq, opts ...http.CallOption) (*ProviderReply, error) {
	var out ProviderReply
	pattern := "/api/cdn/admin/providers/{id}/toggle"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCdnToggleProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateProvider 更新厂商；config 传入字段重加密合并，空值保留原值
func (c *CdnHTTPClientImpl) UpdateProvider(ctx context.Context, in *UpdateProviderReq, opts ...http.CallOption) (*ProviderReply, error) {
	var out ProviderReply
	pattern := "/api/cdn/admin/providers/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCdnUpdateProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
