// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: payment/v1/payment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPaymentCreateOrder = "/payment.v1.Payment/CreateOrder"
const OperationPaymentGetOrder = "/payment.v1.Payment/GetOrder"
const OperationPaymentListMethods = "/payment.v1.Payment/ListMethods"
const OperationPaymentWebhook = "/payment.v1.Payment/Webhook"

type PaymentHTTPServer interface {
	// CreateOrder 创建 VIP 订单：plan=monthly|quarterly|yearly；返回支付跳转 URL（登录态）
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderReply, error)
	// GetOrder 查询订单状态（登录态，只允许查自己的）
	GetOrder(context.Context, *GetOrderReq) (*GetOrderReply, error)
	// ListMethods 支付方式列表：enabled 且 lang/region 匹配，sort 升序（公开）
	ListMethods(context.Context, *ListMethodsReq) (*ListMethodsReply, error)
	// Webhook 渠道回调（stripe/nowpayments，无鉴权，验签在内部）
	Webhook(context.Context, *WebhookReq) (*EmptyReply, error)
}

func RegisterPaymentHTTPServer(s *http.Server, srv PaymentHTTPServer) {
	r := s.Route("/")
	r.POST("/api/payments/order", _Payment_CreateOrder0_HTTP_Handler(srv))
	r.GET("/api/payments/order/{order_no}", _Payment_GetOrder0_HTTP_Handler(srv))
	r.GET("/api/payments/methods", _Payment_ListMethods0_HTTP_Handler(srv))
	r.POST("/api/payments/webhook/{provider}", _Payment_Webhook0_HTTP_Handler(srv))
}

func _Payment_CreateOrder0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentCreateOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Payment_GetOrder0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentGetOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrder(ctx, req.(*GetOrderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Payment_ListMethods0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMethodsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentListMethods)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMethods(ctx, req.(*ListMethodsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMethodsReply)
		return ctx.Result(200, reply)
	}
}

func _Payment_Webhook0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WebhookReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentWebhook)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Webhook(ctx, req.(*WebhookReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

type PaymentHTTPClient interface {
	// CreateOrder 创建 VIP 订单：plan=monthly|quarterly|yearly；返回支付跳转 URL（登录态）
	CreateOrder(ctx context.Context, req *CreateOrderReq, opts ...http.CallOption) (rsp *CreateOrderReply, err error)
	// GetOrder 查询订单状态（登录态，只允许查自己的）
	GetOrder(ctx context.Context, req *GetOrderReq, opts ...http.CallOption) (rsp *GetOrderReply, err error)
	// ListMethods 支付方式列表：enabled 且 lang/region 匹配，sort 升序（公开）
	ListMethods(ctx context.Context, req *ListMethodsReq, opts ...http.CallOption) (rsp *ListMethodsReply, err error)
	// Webhook 渠道回调（stripe/nowpayments，无鉴权，验签在内部）
	Webhook(ctx context.Context, req *WebhookReq, opts ...http.CallOption) (rsp *EmptyReply, err error)
}

type PaymentHTTPClientImpl struct {
	cc *http.Client
}

func NewPaymentHTTPClient(client *http.Client) PaymentHTTPClient {
	return &PaymentHTTPClientImpl{client}
}

// CreateOrder 创建 VIP 订单：plan=monthly|quarterly|yearly；返回支付跳转 URL（登录态）
func (c *PaymentHTTPClientImpl) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...http.CallOption) (*CreateOrderReply, error) {
	var out CreateOrderReply
	pattern := "/api/payments/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentCreateOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetOrder 查询订单状态（登录态，只允许查自己的）
func (c *PaymentHTTPClientImpl) GetOrder(ctx context.Context, in *GetOrderReq, opts ...http.CallOption) (*GetOrderReply, error) {
	var out GetOrderReply
	pattern := "/api/payments/order/{order_no}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentGetOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMethods 支付方式列表：enabled 且 lang/region 匹配，sort 升序（公开）
func (c *PaymentHTTPClientImpl) ListMethods(ctx context.Context, in *ListMethodsReq, opts ...http.CallOption) (*ListMethodsReply, error) {
	var out ListMethodsReply
	pattern := "/api/payments/methods"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentListMethods))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Webhook 渠道回调（stripe/nowpayments，无鉴权，验签在内部）
func (c *PaymentHTTPClientImpl) Webhook(ctx context.Context, in *WebhookReq, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/api/payments/webhook/{provider}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentWebhook))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
