// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: payment/v1/payment.proto

// 支付服务：VIP 下单 / 查单 / 支付方式列表 / 渠道 webhook（任务 T-P-03~08）
// 业务码段 19xxxx；CreateOrder/GetOrder 需登录，ListMethods/Webhook 公开。

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          string                 `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"` // monthly|quarterly|yearly
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"` // 语言，如 "en"；决定默认支付方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderReq) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *CreateOrderReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                             // 金额，单位分
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                          // USD
	CheckoutUrl   string                 `protobuf:"bytes,4,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"` // 支付跳转 URL
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`                          // 渠道码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderReply) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderReply) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *CreateOrderReply) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0待支付 1已支付 2失败 3已关闭
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // 分
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	TxId          string                 `protobuf:"bytes,6,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	PaidAt        string                 `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetOrderReply) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetOrderReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetOrderReply) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetOrderReply) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *GetOrderReply) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type ListMethodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMethodsReq) Reset() {
	*x = ListMethodsReq{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMethodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsReq) ProtoMessage() {}

func (x *ListMethodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsReq.ProtoReflect.Descriptor instead.
func (*ListMethodsReq) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ListMethodsReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type ListMethodsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MethodItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMethodsReply) Reset() {
	*x = ListMethodsReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMethodsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsReply) ProtoMessage() {}

func (x *ListMethodsReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsReply.ProtoReflect.Descriptor instead.
func (*ListMethodsReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListMethodsReply) GetList() []*MethodItem {
	if x != nil {
		return x.List
	}
	return nil
}

type MethodItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`     // 渠道码：stripe/np_usdt
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`     // 'en' 或 '*'
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"` // 'US' 或 '*'
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodItem) Reset() {
	*x = MethodItem{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodItem) ProtoMessage() {}

func (x *MethodItem) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodItem.ProtoReflect.Descriptor instead.
func (*MethodItem) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *MethodItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MethodItem) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *MethodItem) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *MethodItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type WebhookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`              // 渠道码：stripe/nowpayments
	RawBody       []byte                 `protobuf:"bytes,2,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty"` // 原始 body（透传验签）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookReq) Reset() {
	*x = WebhookReq{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookReq) ProtoMessage() {}

func (x *WebhookReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookReq.ProtoReflect.Descriptor instead.
func (*WebhookReq) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *WebhookReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WebhookReq) GetRawBody() []byte {
	if x != nil {
		return x.RawBody
	}
	return nil
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\x1a\x1cgoogle/api/annotations.proto\"8\n" +
	"\x0eCreateOrderReq\x12\x12\n" +
	"\x04plan\x18\x01 \x01(\tR\x04plan\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"\xa0\x01\n" +
	"\x10CreateOrderReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12!\n" +
	"\fcheckout_url\x18\x04 \x01(\tR\vcheckoutUrl\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\"(\n" +
	"\vGetOrderReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"\xc0\x01\n" +
	"\rGetOrderReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x13\n" +
	"\x05tx_id\x18\x06 \x01(\tR\x04txId\x12\x17\n" +
	"\apaid_at\x18\a \x01(\tR\x06paidAt\"$\n" +
	"\x0eListMethodsReq\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\">\n" +
	"\x10ListMethodsReply\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.payment.v1.MethodItemR\x04list\"`\n" +
	"\n" +
	"MethodItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\"C\n" +
	"\n" +
	"WebhookReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\braw_body\x18\x02 \x01(\fR\arawBody\"\f\n" +
	"\n" +
	"EmptyReply2\xaa\x03\n" +
	"\aPayment\x12g\n" +
	"\vCreateOrder\x12\x1a.payment.v1.CreateOrderReq\x1a\x1c.payment.v1.CreateOrderReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/payments/order\x12f\n" +
	"\bGetOrder\x12\x17.payment.v1.GetOrderReq\x1a\x19.payment.v1.GetOrderReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/payments/order/{order_no}\x12f\n" +
	"\vListMethods\x12\x1a.payment.v1.ListMethodsReq\x1a\x1c.payment.v1.ListMethodsReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/payments/methods\x12f\n" +
	"\aWebhook\x12\x16.payment.v1.WebhookReq\x1a\x16.payment.v1.EmptyReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/payments/webhook/{provider}B&Z$open-novel/backend/api/payment/v1;v1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payment_v1_payment_proto_goTypes = []any{
	(*CreateOrderReq)(nil),   // 0: payment.v1.CreateOrderReq
	(*CreateOrderReply)(nil), // 1: payment.v1.CreateOrderReply
	(*GetOrderReq)(nil),      // 2: payment.v1.GetOrderReq
	(*GetOrderReply)(nil),    // 3: payment.v1.GetOrderReply
	(*ListMethodsReq)(nil),   // 4: payment.v1.ListMethodsReq
	(*ListMethodsReply)(nil), // 5: payment.v1.ListMethodsReply
	(*MethodItem)(nil),       // 6: payment.v1.MethodItem
	(*WebhookReq)(nil),       // 7: payment.v1.WebhookReq
	(*EmptyReply)(nil),       // 8: payment.v1.EmptyReply
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	6, // 0: payment.v1.ListMethodsReply.list:type_name -> payment.v1.MethodItem
	0, // 1: payment.v1.Payment.CreateOrder:input_type -> payment.v1.CreateOrderReq
	2, // 2: payment.v1.Payment.GetOrder:input_type -> payment.v1.GetOrderReq
	4, // 3: payment.v1.Payment.ListMethods:input_type -> payment.v1.ListMethodsReq
	7, // 4: payment.v1.Payment.Webhook:input_type -> payment.v1.WebhookReq
	1, // 5: payment.v1.Payment.CreateOrder:output_type -> payment.v1.CreateOrderReply
	3, // 6: payment.v1.Payment.GetOrder:output_type -> payment.v1.GetOrderReply
	5, // 7: payment.v1.Payment.ListMethods:output_type -> payment.v1.ListMethodsReply
	8, // 8: payment.v1.Payment.Webhook:output_type -> payment.v1.EmptyReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
