// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: search/v1/search.proto

// 搜索服务：OpenSearch 多语言检索 / 热门 / 索引同步（任务 #21）
// 业务码段 16xxxx；索引文档按书籍维度，每书一文档，含 zh/en/ja/ko 四语字段

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Search_SearchBooks_FullMethodName = "/search.v1.Search/SearchBooks"
	Search_HotSearches_FullMethodName = "/search.v1.Search/HotSearches"
	Search_HotKeywords_FullMethodName = "/search.v1.Search/HotKeywords"
	Search_SyncIndex_FullMethodName   = "/search.v1.Search/SyncIndex"
	Search_DeleteIndex_FullMethodName = "/search.v1.Search/DeleteIndex"
)

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchClient interface {
	// 搜索（lang 缺省 zh-CN；记录搜索日志，best-effort 不阻塞搜索）
	SearchBooks(ctx context.Context, in *SearchBooksReq, opts ...grpc.CallOption) (*SearchBooksReply, error)
	// 热门榜单（缓存 search:hot）
	HotSearches(ctx context.Context, in *HotSearchesReq, opts ...grpc.CallOption) (*HotSearchesReply, error)
	// 热搜词榜（搜索日志聚合，TOP 10，无鉴权）
	HotKeywords(ctx context.Context, in *HotKeywordsReq, opts ...grpc.CallOption) (*HotKeywordsReply, error)
	// 索引同步（书籍服务在新建/更新书籍或翻译时调用）
	SyncIndex(ctx context.Context, in *SyncIndexReq, opts ...grpc.CallOption) (*SyncIndexReply, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexReq, opts ...grpc.CallOption) (*DeleteIndexReply, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) SearchBooks(ctx context.Context, in *SearchBooksReq, opts ...grpc.CallOption) (*SearchBooksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchBooksReply)
	err := c.cc.Invoke(ctx, Search_SearchBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) HotSearches(ctx context.Context, in *HotSearchesReq, opts ...grpc.CallOption) (*HotSearchesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotSearchesReply)
	err := c.cc.Invoke(ctx, Search_HotSearches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) HotKeywords(ctx context.Context, in *HotKeywordsReq, opts ...grpc.CallOption) (*HotKeywordsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotKeywordsReply)
	err := c.cc.Invoke(ctx, Search_HotKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SyncIndex(ctx context.Context, in *SyncIndexReq, opts ...grpc.CallOption) (*SyncIndexReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncIndexReply)
	err := c.cc.Invoke(ctx, Search_SyncIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) DeleteIndex(ctx context.Context, in *DeleteIndexReq, opts ...grpc.CallOption) (*DeleteIndexReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexReply)
	err := c.cc.Invoke(ctx, Search_DeleteIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations must embed UnimplementedSearchServer
// for forward compatibility.
type SearchServer interface {
	// 搜索（lang 缺省 zh-CN；记录搜索日志，best-effort 不阻塞搜索）
	SearchBooks(context.Context, *SearchBooksReq) (*SearchBooksReply, error)
	// 热门榜单（缓存 search:hot）
	HotSearches(context.Context, *HotSearchesReq) (*HotSearchesReply, error)
	// 热搜词榜（搜索日志聚合，TOP 10，无鉴权）
	HotKeywords(context.Context, *HotKeywordsReq) (*HotKeywordsReply, error)
	// 索引同步（书籍服务在新建/更新书籍或翻译时调用）
	SyncIndex(context.Context, *SyncIndexReq) (*SyncIndexReply, error)
	DeleteIndex(context.Context, *DeleteIndexReq) (*DeleteIndexReply, error)
	mustEmbedUnimplementedSearchServer()
}

// UnimplementedSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServer struct{}

func (UnimplementedSearchServer) SearchBooks(context.Context, *SearchBooksReq) (*SearchBooksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchBooks not implemented")
}
func (UnimplementedSearchServer) HotSearches(context.Context, *HotSearchesReq) (*HotSearchesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HotSearches not implemented")
}
func (UnimplementedSearchServer) HotKeywords(context.Context, *HotKeywordsReq) (*HotKeywordsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HotKeywords not implemented")
}
func (UnimplementedSearchServer) SyncIndex(context.Context, *SyncIndexReq) (*SyncIndexReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncIndex not implemented")
}
func (UnimplementedSearchServer) DeleteIndex(context.Context, *DeleteIndexReq) (*DeleteIndexReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (UnimplementedSearchServer) mustEmbedUnimplementedSearchServer() {}
func (UnimplementedSearchServer) testEmbeddedByValue()                {}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	// If the following call panics, it indicates UnimplementedSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_SearchBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBooksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchBooks(ctx, req.(*SearchBooksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_HotSearches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotSearchesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).HotSearches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_HotSearches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).HotSearches(ctx, req.(*HotSearchesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_HotKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotKeywordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).HotKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_HotKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).HotKeywords(ctx, req.(*HotKeywordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SyncIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SyncIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SyncIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SyncIndex(ctx, req.(*SyncIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_DeleteIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).DeleteIndex(ctx, req.(*DeleteIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.v1.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchBooks",
			Handler:    _Search_SearchBooks_Handler,
		},
		{
			MethodName: "HotSearches",
			Handler:    _Search_HotSearches_Handler,
		},
		{
			MethodName: "HotKeywords",
			Handler:    _Search_HotKeywords_Handler,
		},
		{
			MethodName: "SyncIndex",
			Handler:    _Search_SyncIndex_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _Search_DeleteIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search/v1/search.proto",
}
