// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: search/v1/search.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSearchDeleteIndex = "/search.v1.Search/DeleteIndex"
const OperationSearchHotSearches = "/search.v1.Search/HotSearches"
const OperationSearchSearchBooks = "/search.v1.Search/SearchBooks"
const OperationSearchSyncIndex = "/search.v1.Search/SyncIndex"

type SearchHTTPServer interface {
	DeleteIndex(context.Context, *DeleteIndexReq) (*DeleteIndexReply, error)
	// HotSearches 热门榜单（缓存 search:hot）
	HotSearches(context.Context, *HotSearchesReq) (*HotSearchesReply, error)
	// SearchBooks 搜索（lang 缺省 zh-CN；记录搜索日志，best-effort 不阻塞搜索）
	SearchBooks(context.Context, *SearchBooksReq) (*SearchBooksReply, error)
	// SyncIndex 索引同步（书籍服务在新建/更新书籍或翻译时调用）
	SyncIndex(context.Context, *SyncIndexReq) (*SyncIndexReply, error)
}

func RegisterSearchHTTPServer(s *http.Server, srv SearchHTTPServer) {
	r := s.Route("/")
	r.GET("/api/search", _Search_SearchBooks0_HTTP_Handler(srv))
	r.GET("/api/search/hot", _Search_HotSearches0_HTTP_Handler(srv))
	r.POST("/api/search/index/{book_id}", _Search_SyncIndex0_HTTP_Handler(srv))
	r.DELETE("/api/search/index/{book_id}", _Search_DeleteIndex0_HTTP_Handler(srv))
}

func _Search_SearchBooks0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchBooksReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchSearchBooks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchBooks(ctx, req.(*SearchBooksReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchBooksReply)
		return ctx.Result(200, reply)
	}
}

func _Search_HotSearches0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HotSearchesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchHotSearches)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HotSearches(ctx, req.(*HotSearchesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HotSearchesReply)
		return ctx.Result(200, reply)
	}
}

func _Search_SyncIndex0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncIndexReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchSyncIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncIndex(ctx, req.(*SyncIndexReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncIndexReply)
		return ctx.Result(200, reply)
	}
}

func _Search_DeleteIndex0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteIndexReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchDeleteIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteIndex(ctx, req.(*DeleteIndexReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteIndexReply)
		return ctx.Result(200, reply)
	}
}

type SearchHTTPClient interface {
	DeleteIndex(ctx context.Context, req *DeleteIndexReq, opts ...http.CallOption) (rsp *DeleteIndexReply, err error)
	// HotSearches 热门榜单（缓存 search:hot）
	HotSearches(ctx context.Context, req *HotSearchesReq, opts ...http.CallOption) (rsp *HotSearchesReply, err error)
	// SearchBooks 搜索（lang 缺省 zh-CN；记录搜索日志，best-effort 不阻塞搜索）
	SearchBooks(ctx context.Context, req *SearchBooksReq, opts ...http.CallOption) (rsp *SearchBooksReply, err error)
	// SyncIndex 索引同步（书籍服务在新建/更新书籍或翻译时调用）
	SyncIndex(ctx context.Context, req *SyncIndexReq, opts ...http.CallOption) (rsp *SyncIndexReply, err error)
}

type SearchHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchHTTPClient(client *http.Client) SearchHTTPClient {
	return &SearchHTTPClientImpl{client}
}

func (c *SearchHTTPClientImpl) DeleteIndex(ctx context.Context, in *DeleteIndexReq, opts ...http.CallOption) (*DeleteIndexReply, error) {
	var out DeleteIndexReply
	pattern := "/api/search/index/{book_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchDeleteIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HotSearches 热门榜单（缓存 search:hot）
func (c *SearchHTTPClientImpl) HotSearches(ctx context.Context, in *HotSearchesReq, opts ...http.CallOption) (*HotSearchesReply, error) {
	var out HotSearchesReply
	pattern := "/api/search/hot"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchHotSearches))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchBooks 搜索（lang 缺省 zh-CN；记录搜索日志，best-effort 不阻塞搜索）
func (c *SearchHTTPClientImpl) SearchBooks(ctx context.Context, in *SearchBooksReq, opts ...http.CallOption) (*SearchBooksReply, error) {
	var out SearchBooksReply
	pattern := "/api/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchSearchBooks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SyncIndex 索引同步（书籍服务在新建/更新书籍或翻译时调用）
func (c *SearchHTTPClientImpl) SyncIndex(ctx context.Context, in *SyncIndexReq, opts ...http.CallOption) (*SyncIndexReply, error) {
	var out SyncIndexReply
	pattern := "/api/search/index/{book_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSearchSyncIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
