// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.28.3
// source: recommendation/v1/recommendation.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRecommendationGetRecommendations = "/recommendation.v1.Recommendation/GetRecommendations"

type RecommendationHTTPServer interface {
	// GetRecommendations 推荐列表：strategy = hot | new（缺省 hot）；缓存 recommend:{strategy}:{page}:{page_size}
	GetRecommendations(context.Context, *GetRecommendationsReq) (*GetRecommendationsReply, error)
}

func RegisterRecommendationHTTPServer(s *http.Server, srv RecommendationHTTPServer) {
	r := s.Route("/")
	r.GET("/api/recommend", _Recommendation_GetRecommendations0_HTTP_Handler(srv))
}

func _Recommendation_GetRecommendations0_HTTP_Handler(srv RecommendationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRecommendationsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRecommendationGetRecommendations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRecommendations(ctx, req.(*GetRecommendationsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRecommendationsReply)
		return ctx.Result(200, reply)
	}
}

type RecommendationHTTPClient interface {
	// GetRecommendations 推荐列表：strategy = hot | new（缺省 hot）；缓存 recommend:{strategy}:{page}:{page_size}
	GetRecommendations(ctx context.Context, req *GetRecommendationsReq, opts ...http.CallOption) (rsp *GetRecommendationsReply, err error)
}

type RecommendationHTTPClientImpl struct {
	cc *http.Client
}

func NewRecommendationHTTPClient(client *http.Client) RecommendationHTTPClient {
	return &RecommendationHTTPClientImpl{client}
}

// GetRecommendations 推荐列表：strategy = hot | new（缺省 hot）；缓存 recommend:{strategy}:{page}:{page_size}
func (c *RecommendationHTTPClientImpl) GetRecommendations(ctx context.Context, in *GetRecommendationsReq, opts ...http.CallOption) (*GetRecommendationsReply, error) {
	var out GetRecommendationsReply
	pattern := "/api/recommend"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRecommendationGetRecommendations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
