// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: recommendation/v1/recommendation.proto

// 推荐服务：热门/最新榜单（任务 #15）
// 业务码段 17xxxx；Phase 1 为 MySQL 榜单 stub，Phase 5 接入 AI 推荐（同一契约）

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecommendationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsReq) Reset() {
	*x = GetRecommendationsReq{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsReq) ProtoMessage() {}

func (x *GetRecommendationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsReq.ProtoReflect.Descriptor instead.
func (*GetRecommendationsReq) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendationsReq) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *GetRecommendationsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendationsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RecommendItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Lang          string                 `protobuf:"bytes,6,opt,name=lang,proto3" json:"lang,omitempty"`
	Strategy      string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendItemReply) Reset() {
	*x = RecommendItemReply{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendItemReply) ProtoMessage() {}

func (x *RecommendItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendItemReply.ProtoReflect.Descriptor instead.
func (*RecommendItemReply) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendItemReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *RecommendItemReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecommendItemReply) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *RecommendItemReply) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RecommendItemReply) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *RecommendItemReply) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *RecommendItemReply) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type GetRecommendationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RecommendItemReply  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsReply) Reset() {
	*x = GetRecommendationsReply{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsReply) ProtoMessage() {}

func (x *GetRecommendationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsReply.ProtoReflect.Descriptor instead.
func (*GetRecommendationsReply) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecommendationsReply) GetList() []*RecommendItemReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetRecommendationsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRecommendationsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendationsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_recommendation_v1_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"&recommendation/v1/recommendation.proto\x12\x11recommendation.v1\x1a\x1cgoogle/api/annotations.proto\"d\n" +
	"\x15GetRecommendationsReq\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xbb\x01\n" +
	"\x12RecommendItemReply\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x12\n" +
	"\x04lang\x18\x06 \x01(\tR\x04lang\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\"\x9b\x01\n" +
	"\x17GetRecommendationsReply\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.recommendation.v1.RecommendItemReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\x98\x01\n" +
	"\x0eRecommendation\x12\x85\x01\n" +
	"\x12GetRecommendations\x12(.recommendation.v1.GetRecommendationsReq\x1a*.recommendation.v1.GetRecommendationsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/recommendB-Z+open-novel/backend/api/recommendation/v1;v1b\x06proto3"

var (
	file_recommendation_v1_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_v1_recommendation_proto_rawDescData []byte
)

func file_recommendation_v1_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_v1_recommendation_proto_rawDesc), len(file_recommendation_v1_recommendation_proto_rawDesc)))
	})
	return file_recommendation_v1_recommendation_proto_rawDescData
}

var file_recommendation_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recommendation_v1_recommendation_proto_goTypes = []any{
	(*GetRecommendationsReq)(nil),   // 0: recommendation.v1.GetRecommendationsReq
	(*RecommendItemReply)(nil),      // 1: recommendation.v1.RecommendItemReply
	(*GetRecommendationsReply)(nil), // 2: recommendation.v1.GetRecommendationsReply
}
var file_recommendation_v1_recommendation_proto_depIdxs = []int32{
	1, // 0: recommendation.v1.GetRecommendationsReply.list:type_name -> recommendation.v1.RecommendItemReply
	0, // 1: recommendation.v1.Recommendation.GetRecommendations:input_type -> recommendation.v1.GetRecommendationsReq
	2, // 2: recommendation.v1.Recommendation.GetRecommendations:output_type -> recommendation.v1.GetRecommendationsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recommendation_v1_recommendation_proto_init() }
func file_recommendation_v1_recommendation_proto_init() {
	if File_recommendation_v1_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_v1_recommendation_proto_rawDesc), len(file_recommendation_v1_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_v1_recommendation_proto_depIdxs,
		MessageInfos:      file_recommendation_v1_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_v1_recommendation_proto = out.File
	file_recommendation_v1_recommendation_proto_goTypes = nil
	file_recommendation_v1_recommendation_proto_depIdxs = nil
}
