// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: api/chapter/v1/chapter.proto

// 章节服务：章节 / 正文 / 阅读进度 / 书架（任务 #16）
// 业务码段与通用共用 140xxx 标准码

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chapter_CreateChapter_FullMethodName         = "/chapter.v1.Chapter/CreateChapter"
	Chapter_ListChapters_FullMethodName          = "/chapter.v1.Chapter/ListChapters"
	Chapter_GetChapterContent_FullMethodName     = "/chapter.v1.Chapter/GetChapterContent"
	Chapter_GetReadingProgress_FullMethodName    = "/chapter.v1.Chapter/GetReadingProgress"
	Chapter_UpdateReadingProgress_FullMethodName = "/chapter.v1.Chapter/UpdateReadingProgress"
	Chapter_AddToBookshelf_FullMethodName        = "/chapter.v1.Chapter/AddToBookshelf"
	Chapter_RemoveFromBookshelf_FullMethodName   = "/chapter.v1.Chapter/RemoveFromBookshelf"
	Chapter_ListBookshelf_FullMethodName         = "/chapter.v1.Chapter/ListBookshelf"
)

// ChapterClient is the client API for Chapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChapterClient interface {
	// 新建章节（需登录；章节 + 正文同事务，按 rune 计数）
	CreateChapter(ctx context.Context, in *CreateChapterReq, opts ...grpc.CallOption) (*ChapterReply, error)
	// 章节列表（缓存 chapter:list:{book_id}:{page}:{page_size}）
	ListChapters(ctx context.Context, in *ListChaptersReq, opts ...grpc.CallOption) (*ListChaptersReply, error)
	// 正文（缓存 chapter:content:{book_id}:{chapter_id}:{lang}）
	GetChapterContent(ctx context.Context, in *GetChapterContentReq, opts ...grpc.CallOption) (*ChapterContentReply, error)
	GetReadingProgress(ctx context.Context, in *GetReadingProgressReq, opts ...grpc.CallOption) (*ProgressReply, error)
	UpdateReadingProgress(ctx context.Context, in *UpdateReadingProgressReq, opts ...grpc.CallOption) (*ProgressReply, error)
	AddToBookshelf(ctx context.Context, in *AddToBookshelfReq, opts ...grpc.CallOption) (*ShelfReply, error)
	RemoveFromBookshelf(ctx context.Context, in *RemoveFromBookshelfReq, opts ...grpc.CallOption) (*RemoveFromBookshelfReply, error)
	ListBookshelf(ctx context.Context, in *ListBookshelfReq, opts ...grpc.CallOption) (*ListBookshelfReply, error)
}

type chapterClient struct {
	cc grpc.ClientConnInterface
}

func NewChapterClient(cc grpc.ClientConnInterface) ChapterClient {
	return &chapterClient{cc}
}

func (c *chapterClient) CreateChapter(ctx context.Context, in *CreateChapterReq, opts ...grpc.CallOption) (*ChapterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChapterReply)
	err := c.cc.Invoke(ctx, Chapter_CreateChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) ListChapters(ctx context.Context, in *ListChaptersReq, opts ...grpc.CallOption) (*ListChaptersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChaptersReply)
	err := c.cc.Invoke(ctx, Chapter_ListChapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) GetChapterContent(ctx context.Context, in *GetChapterContentReq, opts ...grpc.CallOption) (*ChapterContentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChapterContentReply)
	err := c.cc.Invoke(ctx, Chapter_GetChapterContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) GetReadingProgress(ctx context.Context, in *GetReadingProgressReq, opts ...grpc.CallOption) (*ProgressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressReply)
	err := c.cc.Invoke(ctx, Chapter_GetReadingProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) UpdateReadingProgress(ctx context.Context, in *UpdateReadingProgressReq, opts ...grpc.CallOption) (*ProgressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressReply)
	err := c.cc.Invoke(ctx, Chapter_UpdateReadingProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) AddToBookshelf(ctx context.Context, in *AddToBookshelfReq, opts ...grpc.CallOption) (*ShelfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShelfReply)
	err := c.cc.Invoke(ctx, Chapter_AddToBookshelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) RemoveFromBookshelf(ctx context.Context, in *RemoveFromBookshelfReq, opts ...grpc.CallOption) (*RemoveFromBookshelfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromBookshelfReply)
	err := c.cc.Invoke(ctx, Chapter_RemoveFromBookshelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) ListBookshelf(ctx context.Context, in *ListBookshelfReq, opts ...grpc.CallOption) (*ListBookshelfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBookshelfReply)
	err := c.cc.Invoke(ctx, Chapter_ListBookshelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChapterServer is the server API for Chapter service.
// All implementations must embed UnimplementedChapterServer
// for forward compatibility.
type ChapterServer interface {
	// 新建章节（需登录；章节 + 正文同事务，按 rune 计数）
	CreateChapter(context.Context, *CreateChapterReq) (*ChapterReply, error)
	// 章节列表（缓存 chapter:list:{book_id}:{page}:{page_size}）
	ListChapters(context.Context, *ListChaptersReq) (*ListChaptersReply, error)
	// 正文（缓存 chapter:content:{book_id}:{chapter_id}:{lang}）
	GetChapterContent(context.Context, *GetChapterContentReq) (*ChapterContentReply, error)
	GetReadingProgress(context.Context, *GetReadingProgressReq) (*ProgressReply, error)
	UpdateReadingProgress(context.Context, *UpdateReadingProgressReq) (*ProgressReply, error)
	AddToBookshelf(context.Context, *AddToBookshelfReq) (*ShelfReply, error)
	RemoveFromBookshelf(context.Context, *RemoveFromBookshelfReq) (*RemoveFromBookshelfReply, error)
	ListBookshelf(context.Context, *ListBookshelfReq) (*ListBookshelfReply, error)
	mustEmbedUnimplementedChapterServer()
}

// UnimplementedChapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChapterServer struct{}

func (UnimplementedChapterServer) CreateChapter(context.Context, *CreateChapterReq) (*ChapterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChapter not implemented")
}
func (UnimplementedChapterServer) ListChapters(context.Context, *ListChaptersReq) (*ListChaptersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChapters not implemented")
}
func (UnimplementedChapterServer) GetChapterContent(context.Context, *GetChapterContentReq) (*ChapterContentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChapterContent not implemented")
}
func (UnimplementedChapterServer) GetReadingProgress(context.Context, *GetReadingProgressReq) (*ProgressReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadingProgress not implemented")
}
func (UnimplementedChapterServer) UpdateReadingProgress(context.Context, *UpdateReadingProgressReq) (*ProgressReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReadingProgress not implemented")
}
func (UnimplementedChapterServer) AddToBookshelf(context.Context, *AddToBookshelfReq) (*ShelfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToBookshelf not implemented")
}
func (UnimplementedChapterServer) RemoveFromBookshelf(context.Context, *RemoveFromBookshelfReq) (*RemoveFromBookshelfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromBookshelf not implemented")
}
func (UnimplementedChapterServer) ListBookshelf(context.Context, *ListBookshelfReq) (*ListBookshelfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBookshelf not implemented")
}
func (UnimplementedChapterServer) mustEmbedUnimplementedChapterServer() {}
func (UnimplementedChapterServer) testEmbeddedByValue()                 {}

// UnsafeChapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChapterServer will
// result in compilation errors.
type UnsafeChapterServer interface {
	mustEmbedUnimplementedChapterServer()
}

func RegisterChapterServer(s grpc.ServiceRegistrar, srv ChapterServer) {
	// If the following call panics, it indicates UnimplementedChapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chapter_ServiceDesc, srv)
}

func _Chapter_CreateChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChapterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).CreateChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_CreateChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).CreateChapter(ctx, req.(*CreateChapterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_ListChapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChaptersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).ListChapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_ListChapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).ListChapters(ctx, req.(*ListChaptersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_GetChapterContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChapterContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).GetChapterContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_GetChapterContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).GetChapterContent(ctx, req.(*GetChapterContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_GetReadingProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).GetReadingProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_GetReadingProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).GetReadingProgress(ctx, req.(*GetReadingProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_UpdateReadingProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReadingProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).UpdateReadingProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_UpdateReadingProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).UpdateReadingProgress(ctx, req.(*UpdateReadingProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_AddToBookshelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBookshelfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).AddToBookshelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_AddToBookshelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).AddToBookshelf(ctx, req.(*AddToBookshelfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_RemoveFromBookshelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBookshelfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).RemoveFromBookshelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_RemoveFromBookshelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).RemoveFromBookshelf(ctx, req.(*RemoveFromBookshelfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_ListBookshelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookshelfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).ListBookshelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chapter_ListBookshelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).ListBookshelf(ctx, req.(*ListBookshelfReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Chapter_ServiceDesc is the grpc.ServiceDesc for Chapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chapter.v1.Chapter",
	HandlerType: (*ChapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChapter",
			Handler:    _Chapter_CreateChapter_Handler,
		},
		{
			MethodName: "ListChapters",
			Handler:    _Chapter_ListChapters_Handler,
		},
		{
			MethodName: "GetChapterContent",
			Handler:    _Chapter_GetChapterContent_Handler,
		},
		{
			MethodName: "GetReadingProgress",
			Handler:    _Chapter_GetReadingProgress_Handler,
		},
		{
			MethodName: "UpdateReadingProgress",
			Handler:    _Chapter_UpdateReadingProgress_Handler,
		},
		{
			MethodName: "AddToBookshelf",
			Handler:    _Chapter_AddToBookshelf_Handler,
		},
		{
			MethodName: "RemoveFromBookshelf",
			Handler:    _Chapter_RemoveFromBookshelf_Handler,
		},
		{
			MethodName: "ListBookshelf",
			Handler:    _Chapter_ListBookshelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/chapter/v1/chapter.proto",
}
