// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: comment/v1/comment.proto

// 评论服务：评论 / 点赞 / 举报 / 收藏（任务 #19）
// 业务码段 15xxxx；写操作均需登录（JWT），发布评论/举报有限流

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterId     *int64                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"` // 缺省 = 书籍级
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommentReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *CreateCommentReq) GetChapterId() int64 {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return 0
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        int64                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,3,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"` // 0 = 书籍级
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     uint32                 `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReportCount   uint32                 `protobuf:"varint,8,opt,name=report_count,json=reportCount,proto3" json:"report_count,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentReply) Reset() {
	*x = CommentReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentReply) ProtoMessage() {}

func (x *CommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentReply.ProtoReflect.Descriptor instead.
func (*CommentReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CommentReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *CommentReply) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *CommentReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentReply) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentReply) GetReportCount() uint32 {
	if x != nil {
		return x.ReportCount
	}
	return 0
}

func (x *CommentReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommentReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterId     *int64                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"` // 缺省 = 全部；0 = 仅书籍级
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReq) Reset() {
	*x = ListCommentsReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReq) ProtoMessage() {}

func (x *ListCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReq.ProtoReflect.Descriptor instead.
func (*ListCommentsReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *ListCommentsReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ListCommentsReq) GetChapterId() int64 {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return 0
}

func (x *ListCommentsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCommentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CommentReply        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReply) Reset() {
	*x = ListCommentsReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReply) ProtoMessage() {}

func (x *ListCommentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReply.ProtoReflect.Descriptor instead.
func (*ListCommentsReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{3}
}

func (x *ListCommentsReply) GetList() []*CommentReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListCommentsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCommentsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type LikeCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentReq) Reset() {
	*x = LikeCommentReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReq) ProtoMessage() {}

func (x *LikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReq.ProtoReflect.Descriptor instead.
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *LikeCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnlikeCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentReq) Reset() {
	*x = UnlikeCommentReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentReq) ProtoMessage() {}

func (x *UnlikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentReq.ProtoReflect.Descriptor instead.
func (*UnlikeCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *UnlikeCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReportCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCommentReq) Reset() {
	*x = ReportCommentReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCommentReq) ProtoMessage() {}

func (x *ReportCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCommentReq.ProtoReflect.Descriptor instead.
func (*ReportCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *ReportCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{7}
}

type AddFavoriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteReq) Reset() {
	*x = AddFavoriteReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteReq) ProtoMessage() {}

func (x *AddFavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteReq.ProtoReflect.Descriptor instead.
func (*AddFavoriteReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *AddFavoriteReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type FavoriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        int64                  `protobuf:"varint,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteReply) Reset() {
	*x = FavoriteReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteReply) ProtoMessage() {}

func (x *FavoriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteReply.ProtoReflect.Descriptor instead.
func (*FavoriteReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *FavoriteReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FavoriteReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteReply) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type DelFavoriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelFavoriteReq) Reset() {
	*x = DelFavoriteReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFavoriteReq) ProtoMessage() {}

func (x *DelFavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFavoriteReq.ProtoReflect.Descriptor instead.
func (*DelFavoriteReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{10}
}

func (x *DelFavoriteReq) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type ListFavoritesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesReq) Reset() {
	*x = ListFavoritesReq{}
	mi := &file_comment_v1_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesReq) ProtoMessage() {}

func (x *ListFavoritesReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesReq.ProtoReflect.Descriptor instead.
func (*ListFavoritesReq) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{11}
}

func (x *ListFavoritesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFavoritesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFavoritesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FavoriteReply       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesReply) Reset() {
	*x = ListFavoritesReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesReply) ProtoMessage() {}

func (x *ListFavoritesReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesReply.ProtoReflect.Descriptor instead.
func (*ListFavoritesReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{12}
}

func (x *ListFavoritesReply) GetList() []*FavoriteReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListFavoritesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFavoritesReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFavoritesReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_comment_v1_comment_proto protoreflect.FileDescriptor

const file_comment_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x18comment/v1/comment.proto\x12\n" +
	"comment.v1\x1a\x1cgoogle/api/annotations.proto\"x\n" +
	"\x10CreateCommentReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\"\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03H\x00R\tchapterId\x88\x01\x01\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontentB\r\n" +
	"\v_chapter_id\"\x9f\x02\n" +
	"\fCommentReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x03R\x06bookId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x03 \x01(\x03R\tchapterId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\rR\tlikeCount\x12!\n" +
	"\freport_count\x18\b \x01(\rR\vreportCount\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\x8e\x01\n" +
	"\x0fListCommentsReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\"\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03H\x00R\tchapterId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB\r\n" +
	"\v_chapter_id\"\x88\x01\n" +
	"\x11ListCommentsReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.comment.v1.CommentReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\" \n" +
	"\x0eLikeCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\"\n" +
	"\x10UnlikeCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\"\n" +
	"\x10ReportCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\f\n" +
	"\n" +
	"EmptyReply\")\n" +
	"\x0eAddFavoriteReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"Q\n" +
	"\rFavoriteReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\x03R\x06bookId\")\n" +
	"\x0eDelFavoriteReq\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"C\n" +
	"\x10ListFavoritesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8a\x01\n" +
	"\x12ListFavoritesReply\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.comment.v1.FavoriteReplyR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xdb\x06\n" +
	"\aComment\x12d\n" +
	"\rCreateComment\x12\x1c.comment.v1.CreateCommentReq\x1a\x18.comment.v1.CommentReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/comments\x12d\n" +
	"\fListComments\x12\x1b.comment.v1.ListCommentsReq\x1a\x1d.comment.v1.ListCommentsReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/comments\x12e\n" +
	"\vLikeComment\x12\x1a.comment.v1.LikeCommentReq\x1a\x16.comment.v1.EmptyReply\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/api/v1/comments/{id}/like\x12i\n" +
	"\rUnlikeComment\x12\x1c.comment.v1.UnlikeCommentReq\x1a\x16.comment.v1.EmptyReply\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/comments/{id}/like\x12k\n" +
	"\rReportComment\x12\x1c.comment.v1.ReportCommentReq\x1a\x16.comment.v1.EmptyReply\"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/api/v1/comments/{id}/report\x12n\n" +
	"\vAddFavorite\x12\x1a.comment.v1.AddFavoriteReq\x1a\x19.comment.v1.FavoriteReply\"(\x82\xd3\xe4\x93\x02\"\" /api/v1/books/{book_id}/favorite\x12k\n" +
	"\vDelFavorite\x12\x1a.comment.v1.DelFavoriteReq\x1a\x16.comment.v1.EmptyReply\"(\x82\xd3\xe4\x93\x02\"* /api/v1/books/{book_id}/favorite\x12h\n" +
	"\rListFavorites\x12\x1c.comment.v1.ListFavoritesReq\x1a\x1e.comment.v1.ListFavoritesReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/favoritesB&Z$open-novel/backend/api/comment/v1;v1b\x06proto3"

var (
	file_comment_v1_comment_proto_rawDescOnce sync.Once
	file_comment_v1_comment_proto_rawDescData []byte
)

func file_comment_v1_comment_proto_rawDescGZIP() []byte {
	file_comment_v1_comment_proto_rawDescOnce.Do(func() {
		file_comment_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)))
	})
	return file_comment_v1_comment_proto_rawDescData
}

var file_comment_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_comment_v1_comment_proto_goTypes = []any{
	(*CreateCommentReq)(nil),   // 0: comment.v1.CreateCommentReq
	(*CommentReply)(nil),       // 1: comment.v1.CommentReply
	(*ListCommentsReq)(nil),    // 2: comment.v1.ListCommentsReq
	(*ListCommentsReply)(nil),  // 3: comment.v1.ListCommentsReply
	(*LikeCommentReq)(nil),     // 4: comment.v1.LikeCommentReq
	(*UnlikeCommentReq)(nil),   // 5: comment.v1.UnlikeCommentReq
	(*ReportCommentReq)(nil),   // 6: comment.v1.ReportCommentReq
	(*EmptyReply)(nil),         // 7: comment.v1.EmptyReply
	(*AddFavoriteReq)(nil),     // 8: comment.v1.AddFavoriteReq
	(*FavoriteReply)(nil),      // 9: comment.v1.FavoriteReply
	(*DelFavoriteReq)(nil),     // 10: comment.v1.DelFavoriteReq
	(*ListFavoritesReq)(nil),   // 11: comment.v1.ListFavoritesReq
	(*ListFavoritesReply)(nil), // 12: comment.v1.ListFavoritesReply
}
var file_comment_v1_comment_proto_depIdxs = []int32{
	1,  // 0: comment.v1.ListCommentsReply.list:type_name -> comment.v1.CommentReply
	9,  // 1: comment.v1.ListFavoritesReply.list:type_name -> comment.v1.FavoriteReply
	0,  // 2: comment.v1.Comment.CreateComment:input_type -> comment.v1.CreateCommentReq
	2,  // 3: comment.v1.Comment.ListComments:input_type -> comment.v1.ListCommentsReq
	4,  // 4: comment.v1.Comment.LikeComment:input_type -> comment.v1.LikeCommentReq
	5,  // 5: comment.v1.Comment.UnlikeComment:input_type -> comment.v1.UnlikeCommentReq
	6,  // 6: comment.v1.Comment.ReportComment:input_type -> comment.v1.ReportCommentReq
	8,  // 7: comment.v1.Comment.AddFavorite:input_type -> comment.v1.AddFavoriteReq
	10, // 8: comment.v1.Comment.DelFavorite:input_type -> comment.v1.DelFavoriteReq
	11, // 9: comment.v1.Comment.ListFavorites:input_type -> comment.v1.ListFavoritesReq
	1,  // 10: comment.v1.Comment.CreateComment:output_type -> comment.v1.CommentReply
	3,  // 11: comment.v1.Comment.ListComments:output_type -> comment.v1.ListCommentsReply
	7,  // 12: comment.v1.Comment.LikeComment:output_type -> comment.v1.EmptyReply
	7,  // 13: comment.v1.Comment.UnlikeComment:output_type -> comment.v1.EmptyReply
	7,  // 14: comment.v1.Comment.ReportComment:output_type -> comment.v1.EmptyReply
	9,  // 15: comment.v1.Comment.AddFavorite:output_type -> comment.v1.FavoriteReply
	7,  // 16: comment.v1.Comment.DelFavorite:output_type -> comment.v1.EmptyReply
	12, // 17: comment.v1.Comment.ListFavorites:output_type -> comment.v1.ListFavoritesReply
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_comment_v1_comment_proto_init() }
func file_comment_v1_comment_proto_init() {
	if File_comment_v1_comment_proto != nil {
		return
	}
	file_comment_v1_comment_proto_msgTypes[0].OneofWrappers = []any{}
	file_comment_v1_comment_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_v1_comment_proto_goTypes,
		DependencyIndexes: file_comment_v1_comment_proto_depIdxs,
		MessageInfos:      file_comment_v1_comment_proto_msgTypes,
	}.Build()
	File_comment_v1_comment_proto = out.File
	file_comment_v1_comment_proto_goTypes = nil
	file_comment_v1_comment_proto_depIdxs = nil
}
