// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: api/comment/v1/comment.proto

// 评论服务：评论 / 点赞 / 举报 / 收藏（任务 #19）
// 业务码段 15xxxx；写操作均需登录（JWT），发布评论/举报有限流

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Comment_CreateComment_FullMethodName = "/comment.v1.Comment/CreateComment"
	Comment_ListComments_FullMethodName  = "/comment.v1.Comment/ListComments"
	Comment_LikeComment_FullMethodName   = "/comment.v1.Comment/LikeComment"
	Comment_UnlikeComment_FullMethodName = "/comment.v1.Comment/UnlikeComment"
	Comment_ReportComment_FullMethodName = "/comment.v1.Comment/ReportComment"
	Comment_AddFavorite_FullMethodName   = "/comment.v1.Comment/AddFavorite"
	Comment_DelFavorite_FullMethodName   = "/comment.v1.Comment/DelFavorite"
	Comment_ListFavorites_FullMethodName = "/comment.v1.Comment/ListFavorites"
)

// CommentClient is the client API for Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentClient interface {
	// 发表评论（内容 ≤2000 字符；chapter_id 缺省 = 书籍级评论）
	CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CommentReply, error)
	// 评论列表：chapter_id 缺省 = 全部；0 = 仅书籍级
	ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsReply, error)
	LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*EmptyReply, error)
	UnlikeComment(ctx context.Context, in *UnlikeCommentReq, opts ...grpc.CallOption) (*EmptyReply, error)
	// 举报：置 status=2 待审核
	ReportComment(ctx context.Context, in *ReportCommentReq, opts ...grpc.CallOption) (*EmptyReply, error)
	AddFavorite(ctx context.Context, in *AddFavoriteReq, opts ...grpc.CallOption) (*FavoriteReply, error)
	DelFavorite(ctx context.Context, in *DelFavoriteReq, opts ...grpc.CallOption) (*EmptyReply, error)
	ListFavorites(ctx context.Context, in *ListFavoritesReq, opts ...grpc.CallOption) (*ListFavoritesReply, error)
}

type commentClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentClient(cc grpc.ClientConnInterface) CommentClient {
	return &commentClient{cc}
}

func (c *commentClient) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CommentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentReply)
	err := c.cc.Invoke(ctx, Comment_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsReply)
	err := c.cc.Invoke(ctx, Comment_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Comment_LikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) UnlikeComment(ctx context.Context, in *UnlikeCommentReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Comment_UnlikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) ReportComment(ctx context.Context, in *ReportCommentReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Comment_ReportComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) AddFavorite(ctx context.Context, in *AddFavoriteReq, opts ...grpc.CallOption) (*FavoriteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteReply)
	err := c.cc.Invoke(ctx, Comment_AddFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) DelFavorite(ctx context.Context, in *DelFavoriteReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Comment_DelFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) ListFavorites(ctx context.Context, in *ListFavoritesReq, opts ...grpc.CallOption) (*ListFavoritesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFavoritesReply)
	err := c.cc.Invoke(ctx, Comment_ListFavorites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServer is the server API for Comment service.
// All implementations must embed UnimplementedCommentServer
// for forward compatibility.
type CommentServer interface {
	// 发表评论（内容 ≤2000 字符；chapter_id 缺省 = 书籍级评论）
	CreateComment(context.Context, *CreateCommentReq) (*CommentReply, error)
	// 评论列表：chapter_id 缺省 = 全部；0 = 仅书籍级
	ListComments(context.Context, *ListCommentsReq) (*ListCommentsReply, error)
	LikeComment(context.Context, *LikeCommentReq) (*EmptyReply, error)
	UnlikeComment(context.Context, *UnlikeCommentReq) (*EmptyReply, error)
	// 举报：置 status=2 待审核
	ReportComment(context.Context, *ReportCommentReq) (*EmptyReply, error)
	AddFavorite(context.Context, *AddFavoriteReq) (*FavoriteReply, error)
	DelFavorite(context.Context, *DelFavoriteReq) (*EmptyReply, error)
	ListFavorites(context.Context, *ListFavoritesReq) (*ListFavoritesReply, error)
	mustEmbedUnimplementedCommentServer()
}

// UnimplementedCommentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentServer struct{}

func (UnimplementedCommentServer) CreateComment(context.Context, *CreateCommentReq) (*CommentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentServer) ListComments(context.Context, *ListCommentsReq) (*ListCommentsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedCommentServer) LikeComment(context.Context, *LikeCommentReq) (*EmptyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedCommentServer) UnlikeComment(context.Context, *UnlikeCommentReq) (*EmptyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeComment not implemented")
}
func (UnimplementedCommentServer) ReportComment(context.Context, *ReportCommentReq) (*EmptyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportComment not implemented")
}
func (UnimplementedCommentServer) AddFavorite(context.Context, *AddFavoriteReq) (*FavoriteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFavorite not implemented")
}
func (UnimplementedCommentServer) DelFavorite(context.Context, *DelFavoriteReq) (*EmptyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DelFavorite not implemented")
}
func (UnimplementedCommentServer) ListFavorites(context.Context, *ListFavoritesReq) (*ListFavoritesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFavorites not implemented")
}
func (UnimplementedCommentServer) mustEmbedUnimplementedCommentServer() {}
func (UnimplementedCommentServer) testEmbeddedByValue()                 {}

// UnsafeCommentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServer will
// result in compilation errors.
type UnsafeCommentServer interface {
	mustEmbedUnimplementedCommentServer()
}

func RegisterCommentServer(s grpc.ServiceRegistrar, srv CommentServer) {
	// If the following call panics, it indicates UnimplementedCommentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Comment_ServiceDesc, srv)
}

func _Comment_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CreateComment(ctx, req.(*CreateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ListComments(ctx, req.(*ListCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).LikeComment(ctx, req.(*LikeCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_UnlikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).UnlikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_UnlikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).UnlikeComment(ctx, req.(*UnlikeCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_ReportComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ReportComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_ReportComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ReportComment(ctx, req.(*ReportCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_AddFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).AddFavorite(ctx, req.(*AddFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_DelFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).DelFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_DelFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).DelFavorite(ctx, req.(*DelFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_ListFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFavoritesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ListFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_ListFavorites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ListFavorites(ctx, req.(*ListFavoritesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Comment_ServiceDesc is the grpc.ServiceDesc for Comment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comment.v1.Comment",
	HandlerType: (*CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _Comment_CreateComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _Comment_ListComments_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _Comment_LikeComment_Handler,
		},
		{
			MethodName: "UnlikeComment",
			Handler:    _Comment_UnlikeComment_Handler,
		},
		{
			MethodName: "ReportComment",
			Handler:    _Comment_ReportComment_Handler,
		},
		{
			MethodName: "AddFavorite",
			Handler:    _Comment_AddFavorite_Handler,
		},
		{
			MethodName: "DelFavorite",
			Handler:    _Comment_DelFavorite_Handler,
		},
		{
			MethodName: "ListFavorites",
			Handler:    _Comment_ListFavorites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/comment/v1/comment.proto",
}
